
/***
 	Actual : Sales Gross Adds 6 KPIs (re-aggregate for GEO only)
 	
 	DTAC :
 		DB1S000101	Prepaid Gross Adds : DTAC (Replace AREA_TYPE P, G, H, HH)
 		DB2S000100	Postpaid Gross Adds : DTAC (Replace AREA_TYPE P, G, H, HH)
 		
 	TRUE :
 		TB1S000101	Prepaid Gross Adds : TMH (Replace AREA_TYPE P, G, H, HH)
 		TB2S000100	Postpaid Gross Adds : TMH (Replace AREA_TYPE P, G, H, HH)
 		TB3S000100	TOL Gross Adds - Connected (Replace AREA_TYPE P, G, H, HH)
 		TB4S000100	TVS Gross Adds (Replace AREA_TYPE P, G, H, HH)
***/

-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 20240101 AS V_DAY_START FROM DUAL
)
-->> fetched < 1 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


	-->> DB1S000101	Prepaid Gross Adds : DTAC (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'DB1S000101' AS METRIC_CD, 'Prepaid Gross Adds : DTAC' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'DB1S000101' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('DB1S000101AB', 'DB1S000101AD', 'DB1S000101AH', 'DB1S000101AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('DB1S000101', 'DB1S000101AB', 'DB1S000101AD', 'DB1S000101AH', 'DB1S000101AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'DB1S000101' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('DB1S000101AB', 'DB1S000101AD', 'DB1S000101AH', 'DB1S000101AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('DB1S000101', 'DB1S000101AB', 'DB1S000101AD', 'DB1S000101AH', 'DB1S000101AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_PREPAID_GROSS_ADDS_DTAC
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> DB2S000100	Postpaid Gross Adds : DTAC (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'DB2S000100' AS METRIC_CD, 'Postpaid Gross Adds : DTAC' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'DB2S000100' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('DB2S000100AB', 'DB2S000100AD', 'DB2S000100AH', 'DB2S000100AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('DB2S000100', 'DB2S000100AB', 'DB2S000100AD', 'DB2S000100AH', 'DB2S000100AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'DB2S000100' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('DB2S000100AB', 'DB2S000100AD', 'DB2S000100AH', 'DB2S000100AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('DB2S000100', 'DB2S000100AB', 'DB2S000100AD', 'DB2S000100AH', 'DB2S000100AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_POSTPAID_GROSS_ADDS_DTAC
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> TB1S000101	Prepaid Gross Adds : TMH (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'TB1S000101' AS METRIC_CD, 'Prepaid Gross Adds : TMH' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB1S000101' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB1S000101AB', 'TB1S000101AD', 'TB1S000101AH', 'TB1S000101AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB1S000101', 'TB1S000101AB', 'TB1S000101AD', 'TB1S000101AH', 'TB1S000101AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB1S000101' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB1S000101AB', 'TB1S000101AD', 'TB1S000101AH', 'TB1S000101AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB1S000101', 'TB1S000101AB', 'TB1S000101AD', 'TB1S000101AH', 'TB1S000101AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_PREPAID_GROSS_ADDS_TMH
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> TB2S000100	Postpaid Gross Adds : TMH (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'TB2S000100' AS METRIC_CD, 'Postpaid Gross Adds : TMH' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM (
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB2S000100' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB2S000100AB', 'TB2S000100AD', 'TB2S000100AH', 'TB2S000100AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB2S000100', 'TB2S000100AB', 'TB2S000100AD', 'TB2S000100AH', 'TB2S000100AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB2S000100' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB2S000100AB', 'TB2S000100AD', 'TB2S000100AH', 'TB2S000100AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB2S000100', 'TB2S000100AB', 'TB2S000100AD', 'TB2S000100AH', 'TB2S000100AI')	
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_POSTPAID_GROSS_ADDS_TMH
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> TB3S000100	TOL Gross Adds - Connected (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'TB3S000100' AS METRIC_CD, 'TOL Gross Adds - Connected' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM (
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB3S000100' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB3S000100AB', 'TB3S000100AD', 'TB3S000100AH', 'TB3S000100AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB3S000100', 'TB3S000100AB', 'TB3S000100AD', 'TB3S000100AH', 'TB3S000100AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB3S000100' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB3S000100AB', 'TB3S000100AD', 'TB3S000100AH', 'TB3S000100AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB3S000100', 'TB3S000100AB', 'TB3S000100AD', 'TB3S000100AH', 'TB3S000100AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_TOL_GROSS_ADDS_TMH
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> TB4S000100	TVS Gross Adds (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'TB4S000100' AS METRIC_CD, 'TVS Gross Adds' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM (
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB4S000100' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB4S000100AB', 'TB4S000100AD', 'TB4S000100AH', 'TB4S000100AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB4S000100', 'TB4S000100AB', 'TB4S000100AD', 'TB4S000100AH', 'TB4S000100AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB4S000100' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB4S000100AB', 'TB4S000100AD', 'TB4S000100AH', 'TB4S000100AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB4S000100', 'TB4S000100AB', 'TB4S000100AD', 'TB4S000100AH', 'TB4S000100AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_TVS_GROSS_ADDS_TMH
