
/***
 	Actual : Sales Inflow M1 6 KPIs (re-aggregate for GEO only)
 	
 	DTAC :
 		DB1R000900	Prepaid Inflow M1 : DTAC (Replace AREA_TYPE P, G, H, HH)
 		DB2R000500	Postpaid Inflow M1 : DTAC (Replace AREA_TYPE P, G, H, HH)
 		
 	TRUE :
 		TB1R000900	Prepaid Inflow M1 : TMH (Replace AREA_TYPE P, G, H, HH)
 		TB2R000500	Postpaid Inflow M1 : TMH (Replace AREA_TYPE P, G, H, HH)
 		TB3R000600	TOL Inflow M1 - Connected (Replace AREA_TYPE P, G, H, HH)
 		TB4R001000	TVS Inflow M1 (Replace AREA_TYPE P, G, H, HH)
***/

-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 20240101 AS V_DAY_START FROM DUAL
)
-->> fetched < 1 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


	-->> DB1R000900	Prepaid Inflow M1 : DTAC (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'DB1R000900' AS METRIC_CD, 'Prepaid Inflow M1 : DTAC' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'DB1R000900' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('DB1R000900AB', 'DB1R000900AD', 'DB1R000900AH', 'DB1R000900AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('DB1R000900', 'DB1R000900AB', 'DB1R000900AD', 'DB1R000900AH', 'DB1R000900AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'DB1R000900' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('DB1R000900AB', 'DB1R000900AD', 'DB1R000900AH', 'DB1R000900AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('DB1R000900', 'DB1R000900AB', 'DB1R000900AD', 'DB1R000900AH', 'DB1R000900AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_PREPAID_INFLOW_M1_DTAC
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> DB2R000500	Postpaid Inflow M1 : DTAC (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'DB2R000500' AS METRIC_CD, 'Postpaid Inflow M1 : DTAC' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'DB2R000500' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('DB2R000500AB', 'DB2R000500AD', 'DB2R000500AH', 'DB2R000500AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('DB2R000500', 'DB2R000500AB', 'DB2R000500AD', 'DB2R000500AH', 'DB2R000500AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'DB2R000500' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('DB2R000500AB', 'DB2R000500AD', 'DB2R000500AH', 'DB2R000500AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('DB2R000500', 'DB2R000500AB', 'DB2R000500AD', 'DB2R000500AH', 'DB2R000500AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_POSTPAID_INFLOW_M1_DTAC
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> TB1R000900	Prepaid Inflow M1 : TMH (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'TB1R000900' AS METRIC_CD, 'Prepaid Inflow M1 : TMH' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB1R000900' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB1R000900AB', 'TB1R000900AD', 'TB1R000900AH', 'TB1R000900AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB1R000900', 'TB1R000900AB', 'TB1R000900AD', 'TB1R000900AH', 'TB1R000900AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB1R000900' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB1R000900AB', 'TB1R000900AD', 'TB1R000900AH', 'TB1R000900AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB1R000900', 'TB1R000900AB', 'TB1R000900AD', 'TB1R000900AH', 'TB1R000900AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_PREPAID_INFLOW_M1_TMH
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> TB2R000500	Postpaid Inflow M1 : TMH (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'TB2R000500' AS METRIC_CD, 'Postpaid Inflow M1 : TMH' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB2R000500' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB2R000500AB', 'TB2R000500AD', 'TB2R000500AH', 'TB2R000500AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB2R000500', 'TB2R000500AB', 'TB2R000500AD', 'TB2R000500AH', 'TB2R000500AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB2R000500' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB2R000500AB', 'TB2R000500AD', 'TB2R000500AH', 'TB2R000500AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB2R000500', 'TB2R000500AB', 'TB2R000500AD', 'TB2R000500AH', 'TB2R000500AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_POSTPAID_INFLOW_M1_TMH
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> TB3R000600	TOL Inflow M1 - Connected (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'TB3R000600' AS METRIC_CD, 'TOL Inflow M1 - Connected' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB3R000600' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB3R000600AB', 'TB3R000600AD', 'TB3R000600AH', 'TB3R000600AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB3R000600', 'TB3R000600AB', 'TB3R000600AD', 'TB3R000600AH', 'TB3R000600AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB3R000600' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB3R000600AB', 'TB3R000600AD', 'TB3R000600AH', 'TB3R000600AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB3R000600', 'TB3R000600AB', 'TB3R000600AD', 'TB3R000600AH', 'TB3R000600AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_TOL_INFLOW_M1_CONNECTED
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> TB4R001000	TVS Inflow M1 (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'TB4R001000' AS METRIC_CD, 'TVS Inflow M1' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB4R001000' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB4R001000AB', 'TB4R001000AD', 'TB4R001000AH', 'TB4R001000AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB4R001000', 'TB4R001000AB', 'TB4R001000AD', 'TB4R001000AH', 'TB4R001000AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB4R001000' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB4R001000AB', 'TB4R001000AD', 'TB4R001000AH', 'TB4R001000AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB4R001000', 'TB4R001000AB', 'TB4R001000AD', 'TB4R001000AH', 'TB4R001000AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_TVS_INFLOW_M1
