
/***	
 	Aggregate : Prepaid Conversion M2 to M1(by Channel) : 36 KPIs (All area)
	
	ALL : 12 KPIs(All Channel)
		B1R001100	Prepaid Conversion M2 to M1 = ("B1R001000 Prepaid Inflow M2" / "B1R000900 Prepaid Inflow M1")
		
	DTAC : 12 KPIs(All Channel)
		DB1R001100	Prepaid Conversion M2 to M1 : DTAC = ("DB1R001000 Prepaid Inflow M2 : DTAC" / "DB1R000900 Prepaid Inflow M1 : DTAC")
		
	TRUE : 12 KPIs(All Channel)
		TB1R001100	Prepaid Conversion M2 to M1 : TMH = ("TB1R001000 Prepaid Inflow M2 : TMH" / "TB1R000900 Prepaid Inflow M1 : TMH")
***/
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 2024 AS TM_KEY_YR FROM DUAL
)
-->> fetched - about 2-5 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
	, CURRENT_DATE AS LOAD_DATE, REMARK
	
FROM (

	-->> B1R001100 Prepaid Conversion M2 to M1 = ("B1R001000 Prepaid Inflow M2" / "B1R000900 Prepaid Inflow M1")
	SELECT M2.TM_KEY_DAY
		, REPLACE(M2.METRIC_CD, 'B1R001000', 'B1R001100') AS METRIC_CD
		, REPLACE(M2.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
		, CASE WHEN COALESCE(M1.ACTUAL_AGG_MTH,0) <> 0 THEN (M2.ACTUAL_AGG_MTH / M1.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'ALL' AS COMP_CD, 'A' AS VERSION, M2.AREA_CD, M2.AREA_NAME, M2.AREA_TYPE
		, M2.METRIC_CD||' '||M2.METRIC_NAME||' / '||M1.METRIC_CD||' '||M1.METRIC_NAME AS REMARK
		
	FROM ( -->> B1R001000xx Prepaid Inflow M2 (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
			, TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'B1R001000' OR REGEXP_LIKE(METRIC_CD, '^B1R001000A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M2
	
	LEFT JOIN ( -->> B1R000900xx Prepaid Inflow M1 (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'B1R000900' OR REGEXP_LIKE(METRIC_CD, '^B1R000900A[A-K]$')) 
		AND TM_KEY_MTH >= (SELECT TM_KEY_YR FROM W_PARAM)-1||12 -->> Prev MTH Inflow M1 of M2
	) M1
		ON M2.CHANNEL_CD = M1.CHANNEL_CD
		AND M2.AREA_CD = M1.AREA_CD
		AND M2.PREV_TM_KEY_DAY = M1.TM_KEY_DAY
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 

	-->> DB1R001100	Prepaid Conversion M2 to M1 : DTAC = ("DB1R001000 Prepaid Inflow M2 : DTAC" / "DB1R000900 Prepaid Inflow M1 : DTAC")
	SELECT M2_D.TM_KEY_DAY
		, REPLACE(M2_D.METRIC_CD, 'B1R001000', 'B1R001100') AS METRIC_CD
		, REPLACE(M2_D.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
		, CASE WHEN COALESCE(M1_D.ACTUAL_AGG_MTH,0) <> 0 THEN (M2_D.ACTUAL_AGG_MTH / M1_D.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'DTAC' AS COMP_CD, 'A' AS VERSION, M2_D.AREA_CD, M2_D.AREA_NAME, M2_D.AREA_TYPE
		, M2_D.METRIC_CD||' '||M2_D.METRIC_NAME||' / '||M1_D.METRIC_CD||' '||M1_D.METRIC_NAME AS REMARK
		
	FROM ( -->> DB1R001000xx Prepaid Inflow M2 : DTAC (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
			, TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'DB1R001000' OR REGEXP_LIKE(METRIC_CD, '^DB1R001000A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M2_D
	
	LEFT JOIN ( -->> DB1R000900xx Prepaid Inflow M1 : DTAC (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'DB1R000900' OR REGEXP_LIKE(METRIC_CD, '^DB1R000900A[A-K]$')) 
		AND TM_KEY_MTH >= (SELECT TM_KEY_YR FROM W_PARAM)-1||12 -->> Prev MTH Inflow M1 of M2
	) M1_D
		ON M2_D.CHANNEL_CD = M1_D.CHANNEL_CD
		AND M2_D.AREA_CD = M1_D.AREA_CD
		AND M2_D.PREV_TM_KEY_DAY = M1_D.TM_KEY_DAY
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 

	-->> TB1R001100 Prepaid Conversion M2 to M1 : TMH = ("TB1R001000 Prepaid Inflow M2 : TMH" / "TB1R000900 Prepaid Inflow M1 : TMH")
	SELECT M2_T.TM_KEY_DAY
		, REPLACE(M2_T.METRIC_CD, 'B1R001000', 'B1R001100') AS METRIC_CD
		, REPLACE(M2_T.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
		, CASE WHEN COALESCE(M1_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M2_T.ACTUAL_AGG_MTH / M1_T.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'TRUE' AS COMP_CD, 'A' AS VERSION, M2_T.AREA_CD, M2_T.AREA_NAME, M2_T.AREA_TYPE
		, M2_T.METRIC_CD||' '||M2_T.METRIC_NAME||' / '||M1_T.METRIC_CD||' '||M1_T.METRIC_NAME AS REMARK
		
	FROM ( -->> TB1R001000xx Prepaid Inflow M2 : TMH (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
			, TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB1R001000' OR REGEXP_LIKE(METRIC_CD, '^TB1R001000A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M2_T
	
	LEFT JOIN ( -->> TB1R000900xx Prepaid Inflow M1 : TMH (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB1R000900' OR REGEXP_LIKE(METRIC_CD, '^TB1R000900A[A-K]$')) 
		AND TM_KEY_MTH >= (SELECT TM_KEY_YR FROM W_PARAM)-1||12 -->> Prev MTH Inflow M1 of M2
	) M1_T
		ON M2_T.CHANNEL_CD = M1_T.CHANNEL_CD
		AND M2_T.AREA_CD = M1_T.AREA_CD
		AND M2_T.PREV_TM_KEY_DAY = M1_T.TM_KEY_DAY
	
) PREPAID_CVS_M2_TO_M1_BY_CHANNEL
