
/***
 	Target : Sales Inflow M1 6 KPIs (for split Corporate, Nationwide)
 	
 	DTAC :
 		DB1R000900	Prepaid Inflow M1 : DTAC ("P" only)
 		DB2R010503	Postpaid Inflow M1 B2C : DTAC (New KPI all Area)
 		
 	TRUE :
 		TB1R000900	Prepaid Inflow M1 : TMH ("P" only)
 		TB2R010503	Postpaid Inflow M1 B2C : TMH (New KPI all Area)
 		TB3R000600	TOL Inflow M1 - Connected ("P" only)
 		TB4R001000	TVS Inflow M1 ("P" only)
***/

-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 20240101 AS V_DAY_START FROM DUAL
)
-->> fetched - about 15-20 sec.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME
	, TARGET_NUMERATOR - COALESCE(TARGET_DENOMINATOR,0) AS TARGET -->> Target Calculation
	, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
	, CURRENT_DATE AS LOAD_DATE, REMARK
	
FROM ( 
	
	-->> DB1R000900	Prepaid Inflow M1 : DTAC ("P" only)
	SELECT TM_KEY_DAY, 'DB1R000900' AS METRIC_CD, 'Prepaid Inflow M1 : DTAC' AS METRIC_NAME
		, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD, 'Nationwide' AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'DB1R000900' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('DB1R000900AB', 'DB1R000900AD', 'DB1R000900AH', 'DB1R000900AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"DB1R000900 Prepaid Inflow M1 : DTAC" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('DB1R000900', 'DB1R000900AB', 'DB1R000900AD', 'DB1R000900AH', 'DB1R000900AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE = 'G' -->> Sum to Nationwide(Geo)
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION
	
	UNION ALL 
	
	-->> DB2R010503	Postpaid Inflow M1 B2C : DTAC (New KPI all Area)
	SELECT TM_KEY_DAY, 'DB2R010503' AS METRIC_CD, 'Postpaid Inflow M1 B2C : DTAC' AS METRIC_NAME
		, COMP_CD, VERSION, AREA_TYPE, AREA_CD, AREA_DESC AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'DB2R000500' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('DB2R000500AB', 'DB2R000500AD', 'DB2R000500AH', 'DB2R000500AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"DB2R000500 Postpaid Inflow M1 : DTAC" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('DB2R000500', 'DB2R000500AB', 'DB2R000500AD', 'DB2R000500AH', 'DB2R000500AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE IN ('P', 'G', 'H', 'HH') -->> B2C Only
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD, AREA_DESC
	
	UNION ALL 
	
	-->> TB1R000900	Prepaid Inflow M1 : TMH ("P" only)
	SELECT TM_KEY_DAY, 'TB1R000900' AS METRIC_CD, 'Prepaid Inflow M1 : TMH' AS METRIC_NAME
		, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD, 'Nationwide' AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'TB1R000900' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('TB1R000900AB', 'TB1R000900AD', 'TB1R000900AH', 'TB1R000900AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"TB1R000900 Prepaid Inflow M1 : TMH" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('TB1R000900', 'TB1R000900AB', 'TB1R000900AD', 'TB1R000900AH', 'TB1R000900AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE = 'G' -->> Sum to Nationwide(Geo)
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION
	
	UNION ALL 
	
	-->> TB2R010503	Postpaid Inflow M1 B2C : TMH (New KPI all Area)
	SELECT TM_KEY_DAY, 'TB2R010503' AS METRIC_CD, 'Postpaid Inflow M1 B2C : TMH' AS METRIC_NAME
		, COMP_CD, VERSION, AREA_TYPE, AREA_CD, AREA_DESC AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'TB2R000500' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('TB2R000500AB', 'TB2R000500AD', 'TB2R000500AH', 'TB2R000500AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"TB2R000500 Postpaid Inflow M1 : TMH" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('TB2R000500', 'TB2R000500AB', 'TB2R000500AD', 'TB2R000500AH', 'TB2R000500AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE IN ('P', 'G', 'H', 'HH') -->> B2C Only
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD, AREA_DESC
	
	UNION ALL 
	
	-->> TB3R000600	TOL Inflow M1 - Connected ("P" only)
	SELECT TM_KEY_DAY, 'TB3R000600' AS METRIC_CD, 'TOL Inflow M1 - Connected' AS METRIC_NAME
		, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD, 'Nationwide' AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'TB3R000600' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('TB3R000600AB', 'TB3R000600AD', 'TB3R000600AH', 'TB3R000600AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"TB3R000600 TOL Inflow M1 - Connected" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('TB3R000600', 'TB3R000600AB', 'TB3R000600AD', 'TB3R000600AH', 'TB3R000600AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE = 'G' -->> Sum to Nationwide(Geo)
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION
	
	UNION ALL
	
	-->> TB4R001000	TVS Inflow M1 ("P" only)
	SELECT TM_KEY_DAY, 'TB4R001000' AS METRIC_CD, 'TVS Inflow M1' AS METRIC_NAME
		, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD, 'Nationwide' AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'TB4R001000' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('TB4R001000AB', 'TB4R001000AD', 'TB4R001000AH', 'TB4R001000AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"TB4R001000 TVS Inflow M1" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('TB4R001000', 'TB4R001000AB', 'TB4R001000AD', 'TB4R001000AH', 'TB4R001000AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE = 'G' -->> Sum to Nationwide(Geo)
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION
	
) TARGET_NATIONWIDE_INFLOW_M1
