
/***
 	Target : Sales Gross Adds 6 KPIs (for split Corporate, Nationwide)
 	
 	DTAC :
 		DB1S000101	Prepaid Gross Adds : DTAC ("P" only)
 		DB2S010106	Postpaid Gross Adds B2C : DTAC (New KPI all Area)
 	
 	TRUE :
 		TB1S000101	Prepaid Gross Adds : TMH ("P" only)
 		TB2S010106	Postpaid Gross Adds B2C : TMH (New KPI all Area)
 		TB3S000100	TOL Gross Adds - Connected ("P" only)
 		TB4S000100	TVS Gross Adds ("P" only)
***/

-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 20240101 AS V_DAY_START FROM DUAL
)
-->> fetched - about 15-20 sec.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME
	, TARGET_NUMERATOR - COALESCE(TARGET_DENOMINATOR,0) AS TARGET -->> Target Calculation
	, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
	, CURRENT_DATE AS LOAD_DATE, REMARK
	
FROM ( 
	
	-->> DB1S000101	Prepaid Gross Adds : DTAC ("P" only)
	SELECT TM_KEY_DAY, 'DB1S000101' AS METRIC_CD, 'Prepaid Gross Adds : DTAC' AS METRIC_NAME
		, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD, 'Nationwide' AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'DB1S000101' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('DB1S000101AB', 'DB1S000101AD', 'DB1S000101AH', 'DB1S000101AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"DB1S000101 Prepaid Gross Adds : DTAC" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('DB1S000101', 'DB1S000101AB', 'DB1S000101AD', 'DB1S000101AH', 'DB1S000101AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE = 'G' -->> Sum to Nationwide(Geo)
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION
	
	UNION ALL 
	
	-->> DB2S010106	Postpaid Gross Adds B2C : DTAC (New KPI all Area)
	SELECT TM_KEY_DAY, 'DB2S010106' AS METRIC_CD, 'Postpaid Gross Adds B2C : DTAC' AS METRIC_NAME
		, COMP_CD, VERSION, AREA_TYPE, AREA_CD, AREA_DESC AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'DB2S000100' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('DB2S000100AB', 'DB2S000100AD', 'DB2S000100AH', 'DB2S000100AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"DB2S000100 Postpaid Gross Adds : DTAC" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('DB2S000100', 'DB2S000100AB', 'DB2S000100AD', 'DB2S000100AH', 'DB2S000100AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE IN ('P', 'G', 'H', 'HH') -->> B2C Only
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD, AREA_DESC
	
	UNION ALL 
	
	-->> TB1S000101	Prepaid Gross Adds : TMH ("P" only)
	SELECT TM_KEY_DAY, 'TB1S000101' AS METRIC_CD, 'Prepaid Gross Adds : TMH' AS METRIC_NAME
		, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD, 'Nationwide' AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'TB1S000101' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('TB1S000101AB', 'TB1S000101AD', 'TB1S000101AH', 'TB1S000101AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"TB1S000101 Prepaid Gross Adds : TMH" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('TB1S000101', 'TB1S000101AB', 'TB1S000101AD', 'TB1S000101AH', 'TB1S000101AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE = 'G' -->> Sum to Nationwide(Geo)
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION
	
	UNION ALL 
	
	-->> TB2S010106	Postpaid Gross Adds B2C : TMH (New KPI all Area)
	SELECT TM_KEY_DAY, 'TB2S010106' AS METRIC_CD, 'Postpaid Gross Adds B2C : TMH' AS METRIC_NAME
		, COMP_CD, VERSION, AREA_TYPE, AREA_CD, AREA_DESC AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'TB2S000100' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('TB2S000100AB', 'TB2S000100AD', 'TB2S000100AH', 'TB2S000100AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"TB2S000100 Postpaid Gross Adds : TMH" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('TB2S000100', 'TB2S000100AB', 'TB2S000100AD', 'TB2S000100AH', 'TB2S000100AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE IN ('P', 'G', 'H', 'HH') -->> B2C Only
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD, AREA_DESC
	
	UNION ALL 
	
	-->> TB3S000100	TOL Gross Adds - Connected ("P" only)
	SELECT TM_KEY_DAY, 'TB3S000100' AS METRIC_CD, 'TOL Gross Adds - Connected' AS METRIC_NAME
		, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD, 'Nationwide' AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'TB3S000100' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('TB3S000100AB', 'TB3S000100AD', 'TB3S000100AH', 'TB3S000100AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"TB3S000100 TOL Gross Adds - Connected" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('TB3S000100', 'TB3S000100AB', 'TB3S000100AD', 'TB3S000100AH', 'TB3S000100AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE = 'G' -->> Sum to Nationwide(Geo)
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION
	
	UNION ALL
	
	-->> TB4S000100	TVS Gross Adds ("P" only)
	SELECT TM_KEY_DAY, 'TB4S000100' AS METRIC_CD, 'TVS Gross Adds' AS METRIC_NAME
		, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD, 'Nationwide' AS AREA_NAME
		, SUM(CASE WHEN METRIC_CD = 'TB4S000100' THEN TARGET END) TARGET_NUMERATOR
		, SUM(CASE WHEN METRIC_CD IN ('TB4S000100AB', 'TB4S000100AD', 'TB4S000100AH', 'TB4S000100AI') THEN TARGET END) TARGET_DENOMINATOR
		, '"TB4S000100 TVS Gross Adds" (Exclude B2B, Contact Center, OTHERS, Own Digital)' AS REMARK
	FROM GEOSPCAPPO.FCT_KPI_NEWCO_TARGET 
	WHERE METRIC_CD IN ('TB4S000100', 'TB4S000100AB', 'TB4S000100AD', 'TB4S000100AH', 'TB4S000100AI')
	AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
	AND AREA_TYPE = 'G' -->> Sum to Nationwide(Geo)
	AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-99', 'Z00', '9GZ', 'Unidentified', 'True Corp'))
	GROUP BY TM_KEY_DAY, COMP_CD, VERSION
	
) TARGET_NATIONWIDE_GROSS_ADDS
