CREATE OR REPLACE PROCEDURE GEOSPCAPPO.PRC_STG_KPI_NEWCO_APRU (DATA_AS_OF_DAY  VARCHAR2) AS 

/* ================================================================= */
/* Created date   : 03-OCT-2022                                      */
/* Created by     : Krawin P.                                        */
/* Objective      : Support prc_stg_kpi_newco_total                  */
/* ================================================================= */
/* Modified date  : 12-OCT-2023                                      */
/* Modified by    : Krawin P.                                        */
/* Objective      : Add KPI : TB7R000105 :ARPU TOL- Connected Subs   */
/* ================================================================= */
/* 2024-05-15     : New KPI B7R000101 & B7R000102                    */
/* 2024-05-24     : New KPI B7R000101GEO & B7R000102GEO              */
/* 2024-05-25     : New KPI TB7R000101GEO & TB7R000102GEO            */
/* 2024-06-05     : B7R000101GEO >>> B7R010101 & TB7R000101GEO >>> TB7R010101  */
/* 2024-06-05     : New KPI B2R010600                                          */
/* 2024-06-05     : New KPI B1R001200GEO                                       */
/* 2024-06-05     : New KPI TB1R001200GEO & TB3R000800GEO & TB4R001600GEO      */
/* 2024-07-10     : Re-Code                                                    */
/* 2024-07-18     : Edit KPI B7R010101 & DB7R010101 & TB7R010101      */


V_SNAP_TM_KEY      NUMBER := TO_NUMBER(DATA_AS_OF_DAY) ;
V_TM_YEAR          NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),1,4)) ;
V_TM_MONTH         NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),1,6)) ;
V_TM_DATE          NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),7,2)) ;

V_TM_MONTH_CUR     NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),1,6)) ;
V_TM_MONTH_PREV    NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),1,6)) ;

BEGIN

--ACTUAL
EXECUTE IMMEDIATE 'TRUNCATE TABLE GEOSPCAPPO.STG_KPI_NEWCO_APRU_ACTUAL' ;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_APRU_ACTUAL
     (TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)


/***
    Aggregate : Revenue ARPU 11 KPIs (All area)
    
    ALL :
        B7R000102   Prepaid ARPU = ("B1R000100 Prepaid Revenue" / "B1S000500 Prepaid Usage Subs")
        B7R000101   Postpaid ARPU = ("B2R000100 Postpaid Revenue" / "B2S000500 Postpaid Active Subs")
        B7R010101   Postpaid ARPU B2C = ("B2R010100 Postpaid Revenue B2C" / "B2S010500 Postpaid Active Subs B2C")
        
    DTAC :
        DB7R000102  Prepaid ARPU : DTAC = ("DB1R000100 Prepaid Revenue : DTAC" / "DB1S000500 Prepaid Usage Subs : DTAC")
        DB7R000101  Postpaid ARPU : DTAC = ("DB2R000100 Postpaid Revenue : DTAC" / "DB2S000500 Postpaid Active Subs : DTAC")
        DB7R010101  Postpaid ARPU B2C : DTAC = ("DB2R010100 Postpaid Revenue B2C : DTAC" / "DB2S010500 Postpaid Active Subs B2C : DTAC")
        
    TRUE :
        TB7R000102  Prepaid ARPU : TMH = ("TB1R000100 Prepaid Revenue : TMH" / "TB1S000500 Prepaid Usage Subs : TMH")
        TB7R000101  Postpaid ARPU : TMH = ("TB2R000100 Postpaid Revenue : TMH" / "TB2S000500 Postpaid Active Subs : TMH")
        TB7R010101  Postpaid ARPU B2C : TMH = ("TB2R010100 Postpaid Revenue B2C : TMH" / "TB2S010500 Postpaid Active Subs B2C : TMH")
        TB7R000103  TOL ARPU = ("TB3R000100 TOL Revenue" / "TB3S000500 TOL Active Subs")
        TB7R000104  TVS ARPU = ("TB4R000100 TVS Revenue" / "TB4S000500 TVS Active Subs")
***/
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
    SELECT 2024 AS TM_KEY_YR FROM DUAL
)
-->> fetched - about 3 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME
    , CASE WHEN COALESCE(DENOMINATOR,0) <> 0 THEN (NUMERATOR / DENOMINATOR) END METRIC_VALUE -->> Calculation
    , COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
    , SYSDATE AS LOAD_DATE, REMARK

FROM ( 
    
    -->> B7R000102  Prepaid ARPU = ("B1R000100 Prepaid Revenue" / "B1S000500 Prepaid Usage Subs")
    SELECT TM_KEY_DAY, 'B7R000102' AS METRIC_CD, 'Prepaid ARPU' AS METRIC_NAME
        , 'ALL' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'B1R000100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'B1S000500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"B1R000100 Prepaid Revenue" / "B1S000500 Prepaid Usage Subs"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('B1R000100', 'B1S000500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
    UNION ALL 

    -->> B7R000101  Postpaid ARPU = ("B2R000100 Postpaid Revenue" / "B2S000500 Postpaid Active Subs")
    SELECT TM_KEY_DAY, 'B7R000101' AS METRIC_CD, 'Postpaid ARPU' AS METRIC_NAME
        , 'ALL' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'B2R000100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'B2S000500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"B2R000100 Postpaid Revenue" / "B2S000500 Postpaid Active Subs"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('B2R000100', 'B2S000500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    AND AREA_CD = 'C' -->> Corporate Only
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
    UNION ALL 

    -->> B7R010101  Postpaid ARPU B2C = ("B2R010100 Postpaid Revenue B2C" / "B2S010500 Postpaid Active Subs B2C")
    SELECT TM_KEY_DAY, 'B7R010101' AS METRIC_CD, 'Postpaid ARPU B2C' AS METRIC_NAME
        , 'ALL' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'B2R010100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'B2S010500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"B2R010100 Postpaid Revenue B2C" / "B2S010500 Postpaid Active Subs B2C"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('B2R010100', 'B2S010500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
    UNION ALL
    
    -->> DB7R000102 Prepaid ARPU : DTAC = ("DB1R000100 Prepaid Revenue : DTAC" / "DB1S000500 Prepaid Usage Subs : DTAC")
    SELECT TM_KEY_DAY, 'DB7R000102' AS METRIC_CD, 'Prepaid ARPU : DTAC' AS METRIC_NAME
        , 'DTAC' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'DB1R000100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'DB1S000500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"DB1R000100 Prepaid Revenue : DTAC" / "DB1S000500 Prepaid Usage Subs : DTAC"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('DB1R000100', 'DB1S000500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
    UNION ALL
    
    -->> DB7R000101 Postpaid ARPU : DTAC = ("DB2R000100 Postpaid Revenue : DTAC" / "DB2S000500 Postpaid Active Subs : DTAC")
    SELECT TM_KEY_DAY, 'DB7R000101' AS METRIC_CD, 'Postpaid ARPU : DTAC' AS METRIC_NAME
        , 'DTAC' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'DB2R000100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'DB2S000500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"DB2R000100 Postpaid Revenue : DTAC" / "DB2S000500 Postpaid Active Subs : DTAC"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('DB2R000100', 'DB2S000500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    AND AREA_CD = 'C' -->> Corporate Only
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
    UNION ALL
    
    -->> DB7R010101 Postpaid ARPU B2C : DTAC = ("DB2R010100 Postpaid Revenue B2C : DTAC" / "DB2S010500 Postpaid Active Subs B2C : DTAC")
    SELECT TM_KEY_DAY, 'DB7R010101' AS METRIC_CD, 'Postpaid ARPU B2C : DTAC' AS METRIC_NAME
        , 'DTAC' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'DB2R010100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'DB2S010500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"DB2R010100 Postpaid Revenue B2C : DTAC" / "DB2S010500 Postpaid Active Subs B2C : DTAC"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('DB2R010100', 'DB2S010500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
    UNION ALL
    
    -->> TB7R000102 Prepaid ARPU : TMH = ("TB1R000100 Prepaid Revenue : TMH" / "TB1S000500 Prepaid Usage Subs : TMH")
    SELECT TM_KEY_DAY, 'TB7R000102' AS METRIC_CD, 'Prepaid ARPU : TMH' AS METRIC_NAME
        , 'TRUE' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'TB1R000100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'TB1S000500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"TB1R000100 Prepaid Revenue : TMH" / "TB1S000500 Prepaid Usage Subs : TMH"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('TB1R000100', 'TB1S000500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
    UNION ALL
    
    -->> TB7R000101 Postpaid ARPU : TMH = ("TB2R000100 Postpaid Revenue : TMH" / "TB2S000500 Postpaid Active Subs : TMH")
    SELECT TM_KEY_DAY, 'TB7R000101' AS METRIC_CD, 'Postpaid ARPU : TMH' AS METRIC_NAME
        , 'TRUE' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'TB2R000100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'TB2S000500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"TB2R000100 Postpaid Revenue : TMH" / "TB2S000500 Postpaid Active Subs : TMH"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('TB2R000100', 'TB2S000500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    AND AREA_CD = 'C' -->> Corporate Only
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
    UNION ALL
    
    -->> TB7R010101 Postpaid ARPU B2C : TMH = ("TB2R010100 Postpaid Revenue B2C : TMH" / "TB2S010500 Postpaid Active Subs B2C : TMH")
    SELECT TM_KEY_DAY, 'TB7R010101' AS METRIC_CD, 'Postpaid ARPU B2C : TMH' AS METRIC_NAME
        , 'TRUE' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'TB2R010100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'TB2S010500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"TB2R010100 Postpaid Revenue B2C : TMH" / "TB2S010500 Postpaid Active Subs B2C : TMH"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('TB2R010100', 'TB2S010500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
    UNION ALL
    
    -->> TB7R000103 TOL ARPU = ("TB3R000100 TOL Revenue" / "TB3S000500 TOL Active Subs")
    SELECT TM_KEY_DAY, 'TB7R000103' AS METRIC_CD, 'TOL ARPU' AS METRIC_NAME
        , 'TRUE' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'TB3R000100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'TB3S000500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"TB3R000100 TOL Revenue" / "TB3S000500 TOL Active Subs"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('TB3R000100', 'TB3S000500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
    UNION ALL
    
    -->> TB7R000104 TVS ARPU = ("TB4R000100 TVS Revenue" / "TB4S000500 TVS Active Subs")
    SELECT TM_KEY_DAY, 'TB7R000104' AS METRIC_CD, 'TVS ARPU' AS METRIC_NAME
        , 'TRUE' AS COMP_CD, 'A' AS VERSION, AREA_TYPE, AREA_CD, AREA_NAME
        , SUM(CASE WHEN METRIC_CD = 'TB4R000100' THEN ACTUAL_AGG_MTH END) NUMERATOR
        , SUM(CASE WHEN METRIC_CD = 'TB4S000500' THEN ACTUAL_AGG_MTH END) DENOMINATOR
        , '"TB4R000100 TVS Revenue" / "TB4S000500 TVS Active Subs"' AS REMARK
    FROM GEOSPCAPPO.AGG_PERF_NEWCO 
    WHERE METRIC_CD IN ('TB4R000100', 'TB4S000500')
    AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
    GROUP BY TM_KEY_DAY, AREA_TYPE, AREA_CD, AREA_NAME
    
) ALL_REVENUE_ARPU

;
COMMIT;

END PRC_STG_KPI_NEWCO_APRU ;
