
/*** TB3S000900 : TOL Gross Adds - Connected (Install Location) ***/

-----------------------------------------------------------------------------------------------------------------------

WITH W_PARAM AS 
(
	SELECT 202404 AS V_MTH
		-- , 20240601 AS V_DT 
	FROM DUAL
)
-----------------------------------------------------------------------------------------------------------------------

SELECT /*+ PARALLEL(8)*/ INSTALLATION_DT, APPLICATION_DT, LAST_DT, ASSET_NUM, ORDER_TP, DISCONNECT_TP, BAN_NUM, PROMOTION_CODE, SPEED, PRODUCT, CUST_NAME, ID_NUM, EMP_NUM, PRTNR_CD, EMP_NAME, ENTRY_FEE, BUILDING_ID, BUILDING_NO, HOUSING, SCAB_CODE, LATITUDE, LONGITUDE, INSTLLR_CCAATT, ACCT_TYP, ACCT_SUB_TYP, INSTLTN_CCAATT_CD, BILL_CCAATT_CD, MOST_USE_CCAATT_CD, SL_CCAATT_CD, SOC_NM, SOC_EFF_DT, SOC_EXP_DT, PROD_OFR_DSCR, CNTRCT_TERM--, SEQ
--	, TP.*
--	, W.WAIVE_REASON

FROM
(
    SELECT
	    O.DT_CMPLET AS INSTALLATION_DT, O.DT_ORDR AS APPLICATION_DT, O.DT_CMPLET AS LAST_DT,
	    O.REF_PROD_ID AS ASSET_NUM, O.CUST_ID_TYP AS ORDER_TP,
	    CASE WHEN UPPER(O.PROMO) LIKE 'FTB48%' THEN 'SCHOOL NET' ELSE O.ACTVN_TYP END AS DISCONNECT_TP,
	    O.CUST_ACCT_NBR AS BAN_NUM, O.PROMO AS PROMOTION_CODE, O.SPEED, O.TECH AS PRODUCT,
	    O.CUST_NM AS CUST_NAME, O.CUST_ID_NBR AS ID_NUM,
	    O.DWH_SL_CD AS EMP_NUM, O.REF_PRTNR_CD AS PRTNR_CD, O.SL_PRTNR_NM AS EMP_NAME,
	    O.ENTRY_FEE, O.BLDG_ID AS BUILDING_ID, O.BLDG_NBR AS BUILDING_NO,
	    CASE WHEN O.BLDG_ID IS NOT NULL THEN 'PROPERTY' ELSE 'OTHER' END AS HOUSING,
	    O.SCAB_CODE, O.LATITUDE, O.LONGITUDE, O.INSTLLR_CCAATT,
	    
	    A.ACCT_TYP, A.ACCT_SUB_TYP,
	    E.INSTLTN_CCAATT_CD, E.BILL_CCAATT_CD, E.MOST_USE_CCAATT_CD, E.SL_CCAATT_CD,
	    S.PROD_OFR_NM AS SOC_NM, S.EFF_DT AS SOC_EFF_DT, S.EXP_DT AS SOC_EXP_DT,
	    F.PROD_OFR_DSCR, F.CNTRCT_TERM,
	    ROW_NUMBER() OVER(PARTITION BY P.PROD_KEY ORDER BY S.EFF_DT DESC, CT.SYN_DATE DESC) AS SEQ
	    
--	    G.AREA_SID, G.TDS_PROVINCE_KEY, G.TDS_PROVINCE, G.TDS_CLUSTER, G.TDS_SUB_CLUSTER, G.PROVINCE, G.REGION, G.TDS_GMD, G.HOP_HINT,
--	    CT.CURR_PHONE_NBR,	    
    
    FROM COMMONAPPO.DIM_ORDR_ACTVTN O
    
    INNER JOIN COMMONAPPO.DIM_PROD P 
    	ON O.PROD_KEY = P.PROD_KEY
    	
    LEFT JOIN COMMONAPPO.DIM_ACCT A 
    	ON P.CUST_ACCT_KEY = A.CUST_ACCT_KEY
    	
    LEFT JOIN COMMONAPPO.DIM_PROD_EXT E 
    	ON P.PROD_KEY = E.PROD_KEY
    	
    LEFT JOIN COMMONAPPO.FCT_SUBS_SERVICE S 
    	ON P.PROD_KEY = S.PROD_KEY 
    	AND S.PROD_OFR_TYP = 'D' 
    	AND SUBSTR(S.PROD_OFR_NM,1,5) NOT IN ('DCFMH','DCFCT','PRIVI','DCFID','DCPID') 
   		AND (EXP_DT IS NULL OR TO_CHAR(EXP_DT, 'YYYYMM') >= (SELECT V_MTH FROM W_PARAM))
    	-- AND (EXP_DT IS NULL OR TO_CHAR(EXP_DT, 'YYYYMMDD') >= (SELECT V_DT FROM W_PARAM)) --Test 1 day
    
    LEFT JOIN COMMONAPPO.DIM_OFFER_MV F 
    	ON S.PROD_OFR_KEY = F.PROD_OFR_KEY
    
    LEFT JOIN COMMONAPPO.DIM_CNTCT_CUST CT 
    	ON P.CUST_KEY = CT.CUST_KEY 
    	AND CT.PRIMARY_CONTACT_IND = 1 
    	AND CT.CURR_PHONE_NBR IS NOT NULL
    /*
    LEFT JOIN (
        SELECT AREA_SID
        FROM (
            --SELECT TDS_PROVINCE_KEY, TDS_PROVINCE, TDS_CLUSTER, TDS_SUB_CLUSTER, PROVINCE, TDS_RGM AS REGION, TDS_GMD, AREA_SID, HOP_HINT,
            SELECT TDS_PROVINCE_KEY, END_EFF_DATE, AREA_SID, 
            	ROW_NUMBER() OVER(PARTITION BY TDS_PROVINCE_KEY ORDER BY END_EFF_DATE DESC) AS SEQ
            FROM CDSAPPO.DIM_TDS_AREA_CCAATT
            WHERE UPPER(GROUP_LK) = 'CCAATT'
        ) G_TMP
        WHERE SEQ = 1
    ) G 
    	ON G.AREA_SID = NVL(E.INSTLTN_CCAATT_CD, NVL(E.BILL_CCAATT_CD, NVL(E.SL_CCAATT_CD, E.DWH_CCAATT_CD)))
    */
	
    WHERE 1=1
    AND UPPER(O.PROD_LN) = 'TOL'
    AND UPPER(O.PROMO) NOT LIKE 'TRL%'
    AND P.PROD_SUB_TYP IN ('FT','Q','IF','INF')
   	AND TO_CHAR(DT_CMPLET, 'YYYYMM') = (SELECT V_MTH FROM W_PARAM)
    -- AND TO_CHAR(DT_CMPLET, 'YYYYMMDD') = (SELECT V_DT FROM W_PARAM) --Test 1 day
) O
-----------------------------------------------------------------------------------------------------------------------

WHERE O.SEQ = 1 ;