CREATE OR REPLACE PROCEDURE GEOSPCAPPO.PRC_FCT_KPI_NEWCO_COMMON_KPI (DATA_AS_OF_DAY  VARCHAR2) AS 

/* ================================================================= */
/* Created date   : 16-Apr-2024                                      */
/* Created by     : Krawin P.                                        */
/* Objective      : Support New KPIs (Conversion, GA ARPU/RC)        */
/* ================================================================= */
/* Modified date  :                                                  */
/* Modified by    :                                                  */
/* ================================================================= */
/* 2024-07-10     : Re-Code                                          */
/* 2024-07-18     : Remove KPI B2R010600 & DB2R010600 & TB2R010600	 */


V_SNAP_TM_KEY NUMBER := TO_NUMBER(DATA_AS_OF_DAY) ;
V_TM_YEAR     NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),1,4)) ;
V_TM_MONTH    NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),1,6)) ;
V_TM_DATE     NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),7,2)) ;

BEGIN

EXECUTE IMMEDIATE 'TRUNCATE TABLE GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL';
COMMIT;

--AGG-SALE-TVS GA ARPU(by Channel).sql
INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL
		 (TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)

/***
 	Aggregate : TVS GA ARPU by channel 12 KPIs (All area)
	
	TRUE : 12 KPIs(All Channel)
		TB4R001600	TVS GA ARPU = ("TB4R001000 TVS Inflow M1" / "TB4S000100 TVS Gross Adds")
***/
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 2024 AS TM_KEY_YR FROM DUAL
)
-->> fetched : 1-3 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
	, CURRENT_DATE AS LOAD_DATE, REMARK
	
FROM ( 

	-->> TB4R001600 TVS GA ARPU = ("TB4R001000 TVS Inflow M1" / "TB4S000100 TVS Gross Adds")
	SELECT M1_T.TM_KEY_DAY
		, REPLACE(M1_T.METRIC_CD, 'TB4R001000', 'TB4R001600') AS METRIC_CD
		, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
		, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'TRUE' AS COMP_CD, 'A' AS VERSION, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
		, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
		
	FROM ( -->> TB4R001000xx TB4R001000 TVS Inflow M1 (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB4R001000' OR REGEXP_LIKE(METRIC_CD, '^TB4R001000A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1_T
	
	LEFT JOIN ( -->> TB4S000100xx TB4S000100 TVS Gross Adds (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB4S000100' OR REGEXP_LIKE(METRIC_CD, '^TB4S000100A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA_T
		ON M1_T.CHANNEL_CD = GA_T.CHANNEL_CD
		AND M1_T.AREA_CD = GA_T.AREA_CD
		AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
		
) TVS_GA_ARPU_BY_CHANNEL
;

COMMIT;

--AGG-SALE-TOL GA ARPU(by Channel).sql
INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL
		 (TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)

/***
 	Aggregate : TOL GA ARPU by channel 12 KPIs (All area)
	
	TRUE : 12 KPIs(All Channel)
		TB3R000800	TOL GA ARPU = ("TB3R000600 TOL Inflow M1 - Connected" / "TB3S000100 TOL Gross Adds - Connected")
***/
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 2024 AS TM_KEY_YR FROM DUAL
)
-->> fetched : 1-3 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
	, CURRENT_DATE AS LOAD_DATE, REMARK
	
FROM ( 

	-->> TB3R000800	TOL GA ARPU = ("TB3R000600 TOL Inflow M1 - Connected" / "TB3S000100 TOL Gross Adds - Connected")
	SELECT M1_T.TM_KEY_DAY
		, REPLACE(M1_T.METRIC_CD, 'TB3R000600', 'TB3R000800') AS METRIC_CD
		, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
		, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'TRUE' AS COMP_CD, 'A' AS VERSION, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
		, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
		
	FROM ( -->> TB3R000600xx TOL Inflow M1 - Connected (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB3R000600' OR REGEXP_LIKE(METRIC_CD, '^TB3R000600A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1_T
	
	LEFT JOIN ( -->> TB3S000100xx TOL Gross Adds - Connected (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB3S000100' OR REGEXP_LIKE(METRIC_CD, '^TB3S000100A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA_T
		ON M1_T.CHANNEL_CD = GA_T.CHANNEL_CD
		AND M1_T.AREA_CD = GA_T.AREA_CD
		AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
		
) TOL_GA_ARPU_BY_CHANNEL
;

COMMIT;

--AGG-SALE-Prepaid GA ARPU(by Channel).sql
INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL
		 (TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)

/***
 	Aggregate : Prepaid GA ARPU by channel 36 KPIs (All area)
	
	ALL : 12 KPIs(All Channel)
		B1R001200	Prepaid GA ARPU = ("B1R000900 Prepaid Inflow M1" / "B1S000101 Prepaid Gross Adds")
		
	DTAC : 12 KPIs(All Channel)
		DB1R001200	Prepaid GA ARPU : DTAC = ("DB1R000900 Prepaid Inflow M1 : DTAC" / "DB1S000101 Prepaid Gross Adds : DTAC")
		
	TRUE : 12 KPIs(All Channel)
		TB1R001200	Prepaid GA ARPU : TMH = ("TB1R000900 Prepaid Inflow M1 : TMH" / "TB1S000101 Prepaid Gross Adds : TMH")
***/
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 2024 AS TM_KEY_YR FROM DUAL
)
-->> fetched : 3-5 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
	, CURRENT_DATE AS LOAD_DATE, REMARK
	
FROM ( 
	
	-->> B1R001200 Prepaid GA ARPU = ("B1R000900 Prepaid Inflow M1" / "B1S000101 Prepaid Gross Adds")
	SELECT M1.TM_KEY_DAY
		, REPLACE(M1.METRIC_CD, 'B1R000900', 'B1R001200') AS METRIC_CD
		, REPLACE(M1.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
		, CASE WHEN COALESCE(GA.ACTUAL_AGG_MTH,0) <> 0 THEN (M1.ACTUAL_AGG_MTH / GA.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'ALL' AS COMP_CD, 'A' AS VERSION, M1.AREA_CD, M1.AREA_NAME, M1.AREA_TYPE
		, M1.METRIC_CD||' '||M1.METRIC_NAME||' / '||GA.METRIC_CD||' '||GA.METRIC_NAME AS REMARK
		
	FROM ( -->> B1R000900xx Prepaid Inflow M1 (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'B1R000900' OR REGEXP_LIKE(METRIC_CD, '^B1R000900A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1
	
	LEFT JOIN ( -->> B1S000101xx Prepaid Gross Adds (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'B1S000101' OR REGEXP_LIKE(METRIC_CD, '^B1S000101A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA
		ON M1.CHANNEL_CD = GA.CHANNEL_CD
		AND M1.AREA_CD = GA.AREA_CD
		AND M1.TM_KEY_DAY = GA.TM_KEY_DAY
	-----------------------------------------------------------------------------------------------------------------------
		
	UNION ALL 

	-->> DB1R001200 Prepaid GA ARPU : DTAC = ("DB1R000900 Prepaid Inflow M1 : DTAC" / "DB1S000101 Prepaid Gross Adds : DTAC")
	SELECT M1_D.TM_KEY_DAY
		, REPLACE(M1_D.METRIC_CD, 'DB1R000900', 'DB1R001200') AS METRIC_CD
		, REPLACE(M1_D.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
		, CASE WHEN COALESCE(GA_D.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_D.ACTUAL_AGG_MTH / GA_D.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'DTAC' AS COMP_CD, 'A' AS VERSION, M1_D.AREA_CD, M1_D.AREA_NAME, M1_D.AREA_TYPE
		, M1_D.METRIC_CD||' '||M1_D.METRIC_NAME||' / '||GA_D.METRIC_CD||' '||GA_D.METRIC_NAME AS REMARK
		
	FROM ( -->> DB1R000900xx Prepaid Inflow M1 : DTAC (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'DB1R000900' OR REGEXP_LIKE(METRIC_CD, '^DB1R000900A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1_D
	
	LEFT JOIN ( -->> DB1S000101xx Prepaid Gross Adds : DTAC (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'DB1S000101' OR REGEXP_LIKE(METRIC_CD, '^DB1S000101A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA_D
		ON M1_D.CHANNEL_CD = GA_D.CHANNEL_CD
		AND M1_D.AREA_CD = GA_D.AREA_CD
		AND M1_D.TM_KEY_DAY = GA_D.TM_KEY_DAY
	-----------------------------------------------------------------------------------------------------------------------
		
	UNION ALL 
	
	-->> TB1R001200 Prepaid GA ARPU : TMH = ("TB1R000900 Prepaid Inflow M1 : TMH" / "TB1S000101 Prepaid Gross Adds : TMH")
	SELECT M1_T.TM_KEY_DAY
		, REPLACE(M1_T.METRIC_CD, 'TB1R000900', 'TB1R001200') AS METRIC_CD
		, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
		, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'TRUE' AS COMP_CD, 'A' AS VERSION, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
		, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
		
	FROM ( -->> TB1R000900xx Prepaid Inflow M1 : TMH (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB1R000900' OR REGEXP_LIKE(METRIC_CD, '^TB1R000900A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1_T
	
	LEFT JOIN ( -->> TB1S000101xx Prepaid Gross Adds : TMH (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB1S000101' OR REGEXP_LIKE(METRIC_CD, '^TB1S000101A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA_T
		ON M1_T.CHANNEL_CD = GA_T.CHANNEL_CD
		AND M1_T.AREA_CD = GA_T.AREA_CD
		AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
		
) PREPAID_GA_ARPU_BY_CHANNEL
;

COMMIT;

--AGG-SALE-Prepaid Conversion M2 to M1(by Channel).sql
INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL
		 (TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)


/***	
 	Aggregate : Prepaid Conversion M2 to M1(by Channel) : 36 KPIs (All area)
	
	ALL : 12 KPIs(All Channel)
		B1R001100	Prepaid Conversion M2 to M1 = ("B1R001000 Prepaid Inflow M2" / "B1R000900 Prepaid Inflow M1")
		
	DTAC : 12 KPIs(All Channel)
		DB1R001100	Prepaid Conversion M2 to M1 : DTAC = ("DB1R001000 Prepaid Inflow M2 : DTAC" / "DB1R000900 Prepaid Inflow M1 : DTAC")
		
	TRUE : 12 KPIs(All Channel)
		TB1R001100	Prepaid Conversion M2 to M1 : TMH = ("TB1R001000 Prepaid Inflow M2 : TMH" / "TB1R000900 Prepaid Inflow M1 : TMH")
***/
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 2024 AS TM_KEY_YR FROM DUAL
)
-->> fetched : 2-5 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
	, CURRENT_DATE AS LOAD_DATE, REMARK
	
FROM (

	-->> B1R001100 Prepaid Conversion M2 to M1 = ("B1R001000 Prepaid Inflow M2" / "B1R000900 Prepaid Inflow M1")
	SELECT M2.TM_KEY_DAY
		, REPLACE(M2.METRIC_CD, 'B1R001000', 'B1R001100') AS METRIC_CD
		, REPLACE(M2.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
		, CASE WHEN COALESCE(M1.ACTUAL_AGG_MTH,0) <> 0 THEN (M2.ACTUAL_AGG_MTH / M1.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'ALL' AS COMP_CD, 'A' AS VERSION, M2.AREA_CD, M2.AREA_NAME, M2.AREA_TYPE
		, M2.METRIC_CD||' '||M2.METRIC_NAME||' / '||M1.METRIC_CD||' '||M1.METRIC_NAME AS REMARK
		
	FROM ( -->> B1R001000xx Prepaid Inflow M2 (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
			, TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'B1R001000' OR REGEXP_LIKE(METRIC_CD, '^B1R001000A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M2
	
	LEFT JOIN ( -->> B1R000900xx Prepaid Inflow M1 (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'B1R000900' OR REGEXP_LIKE(METRIC_CD, '^B1R000900A[A-K]$')) 
		AND TM_KEY_MTH >= (SELECT TM_KEY_YR FROM W_PARAM)-1||12 -->> Prev MTH Inflow M1 of M2
	) M1
		ON M2.CHANNEL_CD = M1.CHANNEL_CD
		AND M2.AREA_CD = M1.AREA_CD
		AND M2.PREV_TM_KEY_DAY = M1.TM_KEY_DAY
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 

	-->> DB1R001100	Prepaid Conversion M2 to M1 : DTAC = ("DB1R001000 Prepaid Inflow M2 : DTAC" / "DB1R000900 Prepaid Inflow M1 : DTAC")
	SELECT M2_D.TM_KEY_DAY
		, REPLACE(M2_D.METRIC_CD, 'B1R001000', 'B1R001100') AS METRIC_CD
		, REPLACE(M2_D.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
		, CASE WHEN COALESCE(M1_D.ACTUAL_AGG_MTH,0) <> 0 THEN (M2_D.ACTUAL_AGG_MTH / M1_D.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'DTAC' AS COMP_CD, 'A' AS VERSION, M2_D.AREA_CD, M2_D.AREA_NAME, M2_D.AREA_TYPE
		, M2_D.METRIC_CD||' '||M2_D.METRIC_NAME||' / '||M1_D.METRIC_CD||' '||M1_D.METRIC_NAME AS REMARK
		
	FROM ( -->> DB1R001000xx Prepaid Inflow M2 : DTAC (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
			, TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'DB1R001000' OR REGEXP_LIKE(METRIC_CD, '^DB1R001000A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M2_D
	
	LEFT JOIN ( -->> DB1R000900xx Prepaid Inflow M1 : DTAC (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'DB1R000900' OR REGEXP_LIKE(METRIC_CD, '^DB1R000900A[A-K]$')) 
		AND TM_KEY_MTH >= (SELECT TM_KEY_YR FROM W_PARAM)-1||12 -->> Prev MTH Inflow M1 of M2
	) M1_D
		ON M2_D.CHANNEL_CD = M1_D.CHANNEL_CD
		AND M2_D.AREA_CD = M1_D.AREA_CD
		AND M2_D.PREV_TM_KEY_DAY = M1_D.TM_KEY_DAY
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 

	-->> TB1R001100 Prepaid Conversion M2 to M1 : TMH = ("TB1R001000 Prepaid Inflow M2 : TMH" / "TB1R000900 Prepaid Inflow M1 : TMH")
	SELECT M2_T.TM_KEY_DAY
		, REPLACE(M2_T.METRIC_CD, 'B1R001000', 'B1R001100') AS METRIC_CD
		, REPLACE(M2_T.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
		, CASE WHEN COALESCE(M1_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M2_T.ACTUAL_AGG_MTH / M1_T.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'TRUE' AS COMP_CD, 'A' AS VERSION, M2_T.AREA_CD, M2_T.AREA_NAME, M2_T.AREA_TYPE
		, M2_T.METRIC_CD||' '||M2_T.METRIC_NAME||' / '||M1_T.METRIC_CD||' '||M1_T.METRIC_NAME AS REMARK
		
	FROM ( -->> TB1R001000xx Prepaid Inflow M2 : TMH (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
			, TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB1R001000' OR REGEXP_LIKE(METRIC_CD, '^TB1R001000A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M2_T
	
	LEFT JOIN ( -->> TB1R000900xx Prepaid Inflow M1 : TMH (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB1R000900' OR REGEXP_LIKE(METRIC_CD, '^TB1R000900A[A-K]$')) 
		AND TM_KEY_MTH >= (SELECT TM_KEY_YR FROM W_PARAM)-1||12 -->> Prev MTH Inflow M1 of M2
	) M1_T
		ON M2_T.CHANNEL_CD = M1_T.CHANNEL_CD
		AND M2_T.AREA_CD = M1_T.AREA_CD
		AND M2_T.PREV_TM_KEY_DAY = M1_T.TM_KEY_DAY
	
) PREPAID_CVS_M2_TO_M1_BY_CHANNEL
;

COMMIT;

--AGG-SALE-Postpaid GA RC(by Channel).sql
INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL
		 (TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)

/***
 	Aggregate : Postpaid GA RC by channel 39 KPIs (All area)
	
	ALL : 13 KPIs(All Channel)
		B2R000600	Postpaid GA RC = ("B2R000500 Postpaid Inflow M1" / "B2S000100 Postpaid Gross Adds")
		
	DTAC : 13 KPIs(All Channel)
		DB2R000600	Postpaid GA RC : DTAC = ("DB2R000500 Postpaid Inflow M1 : DTAC" / "DB2S000100 Postpaid Gross Adds : DTAC")
		
	TRUE : 13 KPIs(All Channel)
		TB2R000600	Postpaid GA RC : TMH = ("TB2R000500 Postpaid Inflow M1 : TMH" / "TB2S000100 Postpaid Gross Adds : TMH")
***/
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 2024 AS TM_KEY_YR FROM DUAL
)
-->> fetched : 1-3 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
	, CURRENT_DATE AS LOAD_DATE, REMARK
	
FROM ( 
	
	-->> B2R000600 Postpaid GA RC = ("B2R000500 Postpaid Inflow M1" / "B2S000100 Postpaid Gross Adds")
	SELECT M1.TM_KEY_DAY
		, REPLACE(M1.METRIC_CD, 'B2R000500', 'B2R000600') AS METRIC_CD
		, REPLACE(M1.METRIC_NAME, 'Inflow M1', 'GA RC') AS METRIC_NAME
		, CASE WHEN COALESCE(GA.ACTUAL_AGG_MTH,0) <> 0 THEN (M1.ACTUAL_AGG_MTH / GA.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'ALL' AS COMP_CD, 'A' AS VERSION, M1.AREA_CD, M1.AREA_NAME, M1.AREA_TYPE
		, M1.METRIC_CD||' '||M1.METRIC_NAME||' / '||GA.METRIC_CD||' '||GA.METRIC_NAME AS REMARK
		
	FROM ( -->> B2R000500xx Postpaid Inflow M1 (by Channel)
		SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO NOLOCK
		WHERE (METRIC_CD = 'B2R000500' OR REGEXP_LIKE(METRIC_CD, '^B2R000500A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1
	
	LEFT JOIN ( -->> B2S000100xx Postpaid Gross Adds (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO NOLOCK
		WHERE (METRIC_CD = 'B2S000100' OR REGEXP_LIKE(METRIC_CD, '^B2S000100A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA
		ON M1.CHANNEL_CD = GA.CHANNEL_CD
		AND M1.AREA_CD = GA.AREA_CD
		AND M1.TM_KEY_DAY = GA.TM_KEY_DAY
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	-->> DB2R000600 Postpaid GA RC : DTAC = ("DB2R000500 Postpaid Inflow M1 : DTAC" / "DB2S000100 Postpaid Gross Adds : DTAC")
	SELECT M1_D.TM_KEY_DAY
		, REPLACE(M1_D.METRIC_CD, 'DB2R000500', 'DB2R000600') AS METRIC_CD
		, REPLACE(M1_D.METRIC_NAME, 'Inflow M1', 'GA RC') AS METRIC_NAME
		, CASE WHEN COALESCE(GA_D.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_D.ACTUAL_AGG_MTH / GA_D.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'DTAC' AS COMP_CD, 'A' AS VERSION, M1_D.AREA_CD, M1_D.AREA_NAME, M1_D.AREA_TYPE
		, M1_D.METRIC_CD||' '||M1_D.METRIC_NAME||' / '||GA_D.METRIC_CD||' '||GA_D.METRIC_NAME AS REMARK
		
	FROM ( -->> DB2R000500xx Postpaid Inflow M1 : DTAC (by Channel)
		SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO NOLOCK
		WHERE (METRIC_CD = 'DB2R000500' OR REGEXP_LIKE(METRIC_CD, '^DB2R000500A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1_D
	
	LEFT JOIN ( -->> DB2S000100xx Postpaid Gross Adds : DTAC (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO NOLOCK
		WHERE (METRIC_CD = 'DB2S000100' OR REGEXP_LIKE(METRIC_CD, '^DB2S000100A[A-K]$'))  
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA_D
		ON M1_D.CHANNEL_CD = GA_D.CHANNEL_CD
		AND M1_D.AREA_CD = GA_D.AREA_CD
		AND M1_D.TM_KEY_DAY = GA_D.TM_KEY_DAY
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	-->> TB2R000600	Postpaid GA RC : TMH = ("TB2R000500 Postpaid Inflow M1 : TMH" / "TB2S000100 Postpaid Gross Adds : TMH")
	SELECT M1_T.TM_KEY_DAY
		, REPLACE(M1_T.METRIC_CD, 'TB2R000500', 'TB2R000600') AS METRIC_CD
		, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA RC') AS METRIC_NAME
		, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
		, 'TRUE' AS COMP_CD, 'A' AS VERSION, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
		, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
		
	FROM ( -->> TB2R000500xx Postpaid Inflow M1 : TMH (by Channel)
		SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO NOLOCK
		WHERE (METRIC_CD = 'TB2R000500' OR REGEXP_LIKE(METRIC_CD, '^TB2R000500A[A-K]$'))
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1_T
	
	LEFT JOIN ( -->> TB2S000100xx Postpaid Gross Adds : TMH (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO NOLOCK
		WHERE (METRIC_CD = 'TB2S000100' OR REGEXP_LIKE(METRIC_CD, '^TB2S000100A[A-K]$'))
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA_T
		ON M1_T.CHANNEL_CD = GA_T.CHANNEL_CD
		AND M1_T.AREA_CD = GA_T.AREA_CD
		AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
		
) POSTPAID_GA_RC_BY_CHANNEL
;

COMMIT;

END PRC_FCT_KPI_NEWCO_COMMON_KPI ;
