
/***
 	Actual : Sales Inflow M2 2 KPIs (re-aggregate for GEO only)
 	
 	DTAC :
		DB1R001000	Prepaid Inflow M2 : DTAC (Replace AREA_TYPE P, G, H, HH)
		
 	TRUE :
 		TB1R001000	Prepaid Inflow M2 : TMH (Replace AREA_TYPE P, G, H, HH)
***/

-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 20240101 AS V_DAY_START FROM DUAL
)
-->> fetched < 1 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


	-->> DB1R001000	Prepaid Inflow M2 : DTAC (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'DB1R001000' AS METRIC_CD, 'Prepaid Inflow M2 : DTAC' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'DB1R001000' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('DB1R001000AB', 'DB1R001000AD', 'DB1R001000AH', 'DB1R001000AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('DB1R001000', 'DB1R001000AB', 'DB1R001000AD', 'DB1R001000AH', 'DB1R001000AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'DB1R001000' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('DB1R001000AB', 'DB1R001000AD', 'DB1R001000AH', 'DB1R001000AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('DB1R001000', 'DB1R001000AB', 'DB1R001000AD', 'DB1R001000AH', 'DB1R001000AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_PREPAID_INFLOW_M2_DTAC
	-----------------------------------------------------------------------------------------------------------------------
	
	UNION ALL 
	
	
	-->> TB1R001000	Prepaid Inflow M2 : TMH (Replace AREA_TYPE P, G, H, HH)
	
	SELECT TM_KEY_DAY, 'TB1R001000' AS METRIC_CD, 'Prepaid Inflow M2 : TMH' AS METRIC_NAME
		, ACTUAL_NUMERATOR - COALESCE(ACTUAL_DENOMINATOR,0) AS ACTUAL -->> Actual Calculation
		, COMP_CD, VERSION, AREA_CD--, AREA_NAME
		, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE
		, 'excl. B2B, Contact Center, OTHERS, Own Digital' AS REMARK
	FROM ( 
		-->> Re-aggregate AREA_TYPE ("P" only)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, 'P' AS AREA_TYPE, 'P' AS AREA_CD--, 'Nationwide' AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB1R001000' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB1R001000AB', 'TB1R001000AD', 'TB1R001000AH', 'TB1R001000AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB1R001000', 'TB1R001000AB', 'TB1R001000AD', 'TB1R001000AH', 'TB1R001000AI')
		AND AREA_TYPE = 'G' -->> Sum to Area "P" Nationwide (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION
		
		UNION ALL 
		
		-->> Re-aggregate AREA_TYPE (G, H, HH)
		SELECT TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD--, AREA_DESC AS AREA_NAME
			, SUM(CASE WHEN METRIC_CD = 'TB1R001000' THEN ACTUAL END) ACTUAL_NUMERATOR
			, SUM(CASE WHEN METRIC_CD IN ('TB1R001000AB', 'TB1R001000AD', 'TB1R001000AH', 'TB1R001000AI') THEN ACTUAL END) ACTUAL_DENOMINATOR
		FROM GEOSPCAPPO.FCT_KPI_NEWCO_ACTUAL 
		WHERE METRIC_CD IN ('TB1R001000', 'TB1R001000AB', 'TB1R001000AD', 'TB1R001000AH', 'TB1R001000AI')
		AND AREA_TYPE IN ('G', 'H', 'HH') -->> re-aggregate for Area G, H, HH (GEO only)
		AND NOT (AREA_CD IS NULL OR AREA_CD IN ('-1', '-99', 'Z00', '9GZ', 'GX0', 'Unidentified', 'True Corp'))
		AND TM_KEY_DAY >= (SELECT V_DAY_START FROM W_PARAM)
		GROUP BY TM_KEY_DAY, COMP_CD, VERSION, AREA_TYPE, AREA_CD
	) ACTUAL_PREPAID_INFLOW_M2_TMH
