
/*** Manual step : Initial data for re-run to "AUTOKPI.FCT_BROADBAND_MKS" ***/

-----------------------------------------------------------------------------------------------------------------------

WITH W_PARAM AS
(
	SELECT :initial_mth_start AS V_INI_MTH_START
		, :initial_mth_end AS V_INI_MTH_END
	FROM DUAL
) -->> W_PARAM
-----------------------------------------------------------------------------------------------------------------------

, W_PREP_PERIOD AS 
(
	SELECT TM_KEY_YR, TM_KEY_MTH, TRUE_TM_KEY_WK, TM_KEY_DAY
	FROM CDSAPPO.DIM_TIME NOLOCK
	WHERE TM_KEY_MTH BETWEEN (SELECT V_INI_MTH_START FROM W_PARAM) AND (SELECT V_INI_MTH_END FROM W_PARAM)
) -->> W_PREP_PERIOD
-----------------------------------------------------------------------------------------------------------------------

, W_ORG AS 
( --7,436 row
	SELECT DISTINCT ZONE_TYPE, ORGID_G, TDS_SGMD, ORGID_R, TDS_RGM_CODE, ORGID_H, HOP_HINT, TDS_PROVINCE
		, SUBSTR(CCAATT,1,2) AS PROVINCE_CD, PROVINCE_ENG--, PROVINCE_TH
		, ORGID_HH, D_CLUSTER
		, ORG_ID_A, SUBSTR(CCAATT,1,4) AS CCAA
		, CASE WHEN SUBSTR(CCAATT,1,4) = 1413 THEN 'Bang Saai' ELSE DISTRICT_EN END DISTRICT_EN
		, CASE 	WHEN COUNT(DISTINCT SUBSTR(CCAATT,1,4)) OVER(PARTITION BY CASE WHEN SUBSTR(CCAATT,1,4) = 1413 THEN 'Bang Saai' ELSE DISTRICT_EN END) > 1
				THEN PROVINCE_ENG||'_'||(CASE WHEN SUBSTR(CCAATT,1,4) = 1413 THEN 'Bang Saai' ELSE DISTRICT_EN END)
				ELSE (CASE WHEN SUBSTR(CCAATT,1,4) = 1413 THEN 'Bang Saai' ELSE DISTRICT_EN END)
				END DISTRICT_UNIQUE
		, CCAATT, SUB_DISTRICT_EN
		, COUNT(DISTINCT SUBSTR(CCAATT,1,4)) OVER(PARTITION BY CASE WHEN SUBSTR(CCAATT,1,4) = 1413 THEN 'Bang Saai' ELSE DISTRICT_EN END) AS CNT_DUP_CCAA
	FROM CDSAPPO.DIM_MOOC_AREA NOLOCK
	WHERE REMARK <> 'Dummy'
) -->> W_ORG
-----------------------------------------------------------------------------------------------------------------------

, W_ACTUAL_DIMENSION_INITIAL AS 
(
	SELECT P.TM_KEY_MTH, O.*
	FROM (
		SELECT DISTINCT TM_KEY_MTH 
		FROM W_PREP_PERIOD) P
	INNER JOIN W_ORG O
		ON 1=1
) -->> W_ACTUAL_DIMENSION_INITIAL
-----------------------------------------------------------------------------------------------------------------------

, W_BB_MKS_RAWDATA_INITIAL AS 
(
	SELECT TM_KEY_MTH, ISP, ZONE_TYPE, ORGID_G, TDS_SGMD, ORGID_R, TDS_RGM_CODE, ORGID_H, HOP_HINT, TDS_PROVINCE, PROVINCE_CD, PROVINCE_ENG, ORGID_HH, D_CLUSTER, CCAA, DISTRICT_UNIQUE, CCAATT, SUB_DISTRICT_EN, EAST_FLAG
		, SUM(BASE_SUBS) BASE_SUBS, SUM(SUBS_CHG) SUBS_CHG, SUM(SUBS) SUBS
	FROM (
		SELECT D.TM_KEY_MTH, ISP, BASE_SUBS, SUBS_CHG--, SUBS
			, CASE WHEN SUBS < 0 THEN 0 ELSE SUBS END SUBS
			, D.ZONE_TYPE, D.ORGID_G, D.TDS_SGMD, D.ORGID_R, D.TDS_RGM_CODE, D.ORGID_H, D.HOP_HINT, D.TDS_PROVINCE
			, D.PROVINCE_CD, D.PROVINCE_ENG, D.ORGID_HH, D.D_CLUSTER
			, D.CCAA, D.DISTRICT_UNIQUE, D.CCAATT, D.SUB_DISTRICT_EN
			, CASE WHEN (D.ORGID_G = 'GX3' AND D.HOP_HINT NOT LIKE 'SMP%') THEN 'Y' END EAST_FLAG
		FROM W_ACTUAL_DIMENSION_INITIAL D
		LEFT JOIN CORPNSBOX.FCT_BB_SHARE_SUBS_CCAATT A
			ON D.CCAATT = A.CCAATT
			AND D.TM_KEY_MTH = A.TM_KEY_MTH
			AND A.ISP IN ('3BB','AIS','CAT','TOL','TOT')
			AND A.TM_KEY_MTH BETWEEN (SELECT V_INI_MTH_START FROM W_PARAM) AND (SELECT V_INI_MTH_END FROM W_PARAM)
	) RAWDATA
	GROUP BY TM_KEY_MTH, ISP, ZONE_TYPE, ORGID_G, TDS_SGMD, ORGID_R, TDS_RGM_CODE, ORGID_H, HOP_HINT, TDS_PROVINCE, PROVINCE_CD, PROVINCE_ENG, ORGID_HH, D_CLUSTER, CCAA, DISTRICT_UNIQUE, CCAATT, SUB_DISTRICT_EN, EAST_FLAG
) -->> W_BB_MKS_RAWDATA_INITIAL
-----------------------------------------------------------------------------------------------------------------------

, W_BB_MKS_AGG_1 AS 
(
	SELECT TM_KEY_MTH, ZONE_TYPE, ORGID_G, TDS_SGMD, ORGID_R, TDS_RGM_CODE, ORGID_H, HOP_HINT, TDS_PROVINCE, PROVINCE_CD, PROVINCE_ENG, ORGID_HH, D_CLUSTER, CCAA, DISTRICT_UNIQUE, CCAATT, SUB_DISTRICT_EN, EAST_FLAG
		, SUM(COALESCE(SUBS,0)) AS SUBS_TOTAL
		, SUM(CASE WHEN ISP = '3BB' THEN SUBS ELSE 0 END) AS SUBS_3BB
		, SUM(CASE WHEN ISP = 'AIS' THEN SUBS ELSE 0 END) AS SUBS_AIS
		, SUM(CASE WHEN ISP = 'CAT' THEN SUBS ELSE 0 END) AS SUBS_CAT
		, SUM(CASE WHEN ISP = 'TOL' THEN SUBS ELSE 0 END) AS SUBS_TOL
		, SUM(CASE WHEN ISP = 'TOT' THEN SUBS ELSE 0 END) AS SUBS_TOT
	FROM W_BB_MKS_RAWDATA_INITIAL
	GROUP BY TM_KEY_MTH, ZONE_TYPE, ORGID_G, TDS_SGMD, ORGID_R, TDS_RGM_CODE, ORGID_H, HOP_HINT, TDS_PROVINCE, PROVINCE_CD, PROVINCE_ENG, ORGID_HH, D_CLUSTER, CCAA, DISTRICT_UNIQUE, CCAATT, SUB_DISTRICT_EN, EAST_FLAG
) -->> W_BB_MKS_AGG_1
-----------------------------------------------------------------------------------------------------------------------

, W_BB_MKS_AGG_2 AS 
(
	-->> P : Nationwide
	SELECT TM_KEY_MTH, 1 AS AREA_NO, 'P' AS AREA_TYPE, 'P' AS AREA_CD, 'Nationwide' AS AREA_NAME
		, SUM(SUBS_3BB) AS SUBS_3BB, SUM(SUBS_AIS) AS SUBS_AIS, SUM(SUBS_CAT) AS SUBS_CAT, SUM(SUBS_TOL) AS SUBS_TOL, SUM(SUBS_TOT) AS SUBS_TOT, SUM(SUBS_TOTAL) AS SUBS_TOTAL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_3BB) = 0 THEN 0 ELSE (SUM(SUBS_3BB) / SUM(SUBS_TOTAL)) * 100 END MKS_3BB
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_AIS) = 0 THEN 0 ELSE (SUM(SUBS_AIS) / SUM(SUBS_TOTAL)) * 100 END MKS_AIS
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_CAT) = 0 THEN 0 ELSE (SUM(SUBS_CAT) / SUM(SUBS_TOTAL)) * 100 END MKS_CAT
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOL) = 0 THEN 0 ELSE (SUM(SUBS_TOL) / SUM(SUBS_TOTAL)) * 100 END MKS_TOL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOT) = 0 THEN 0 ELSE (SUM(SUBS_TOT) / SUM(SUBS_TOTAL)) * 100 END MKS_TOT
	FROM W_BB_MKS_AGG_1
	GROUP BY TM_KEY_MTH
	
	UNION ALL 
	
	-->> ZONE : BMA & UPC
	SELECT TM_KEY_MTH, 2 AS AREA_NO, 'Z' AS AREA_TYPE, ZONE_TYPE AS AREA_CD, ZONE_TYPE AS AREA_NAME
		, SUM(SUBS_3BB) AS SUBS_3BB, SUM(SUBS_AIS) AS SUBS_AIS, SUM(SUBS_CAT) AS SUBS_CAT, SUM(SUBS_TOL) AS SUBS_TOL, SUM(SUBS_TOT) AS SUBS_TOT, SUM(SUBS_TOTAL) AS SUBS_TOTAL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_3BB) = 0 THEN 0 ELSE (SUM(SUBS_3BB) / SUM(SUBS_TOTAL)) * 100 END MKS_3BB
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_AIS) = 0 THEN 0 ELSE (SUM(SUBS_AIS) / SUM(SUBS_TOTAL)) * 100 END MKS_AIS
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_CAT) = 0 THEN 0 ELSE (SUM(SUBS_CAT) / SUM(SUBS_TOTAL)) * 100 END MKS_CAT
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOL) = 0 THEN 0 ELSE (SUM(SUBS_TOL) / SUM(SUBS_TOTAL)) * 100 END MKS_TOL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOT) = 0 THEN 0 ELSE (SUM(SUBS_TOT) / SUM(SUBS_TOTAL)) * 100 END MKS_TOT
	FROM W_BB_MKS_AGG_1
	GROUP BY TM_KEY_MTH, ZONE_TYPE
	
	UNION ALL 
	
	-->> ZONE : East
	SELECT TM_KEY_MTH, 3 AS AREA_NO, 'Z' AS AREA_TYPE, 'EAST' AS AREA_CD, 'East' AS AREA_NAME
		, SUM(SUBS_3BB) AS SUBS_3BB, SUM(SUBS_AIS) AS SUBS_AIS, SUM(SUBS_CAT) AS SUBS_CAT, SUM(SUBS_TOL) AS SUBS_TOL, SUM(SUBS_TOT) AS SUBS_TOT, SUM(SUBS_TOTAL) AS SUBS_TOTAL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_3BB) = 0 THEN 0 ELSE (SUM(SUBS_3BB) / SUM(SUBS_TOTAL)) * 100 END MKS_3BB
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_AIS) = 0 THEN 0 ELSE (SUM(SUBS_AIS) / SUM(SUBS_TOTAL)) * 100 END MKS_AIS
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_CAT) = 0 THEN 0 ELSE (SUM(SUBS_CAT) / SUM(SUBS_TOTAL)) * 100 END MKS_CAT
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOL) = 0 THEN 0 ELSE (SUM(SUBS_TOL) / SUM(SUBS_TOTAL)) * 100 END MKS_TOL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOT) = 0 THEN 0 ELSE (SUM(SUBS_TOT) / SUM(SUBS_TOTAL)) * 100 END MKS_TOT
	FROM W_BB_MKS_AGG_1
	WHERE EAST_FLAG = 'Y'
	GROUP BY TM_KEY_MTH, EAST_FLAG
	
	UNION ALL 
	
	-->> MAIN Province : 4 PROVINCE
	SELECT TM_KEY_MTH, 4 AS AREA_NO, 'Z' AS AREA_TYPE, PROVINCE_CD AS AREA_CD, PROVINCE_ENG AS AREA_NAME
		, SUM(SUBS_3BB) AS SUBS_3BB, SUM(SUBS_AIS) AS SUBS_AIS, SUM(SUBS_CAT) AS SUBS_CAT, SUM(SUBS_TOL) AS SUBS_TOL, SUM(SUBS_TOT) AS SUBS_TOT, SUM(SUBS_TOTAL) AS SUBS_TOTAL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_3BB) = 0 THEN 0 ELSE (SUM(SUBS_3BB) / SUM(SUBS_TOTAL)) * 100 END MKS_3BB
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_AIS) = 0 THEN 0 ELSE (SUM(SUBS_AIS) / SUM(SUBS_TOTAL)) * 100 END MKS_AIS
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_CAT) = 0 THEN 0 ELSE (SUM(SUBS_CAT) / SUM(SUBS_TOTAL)) * 100 END MKS_CAT
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOL) = 0 THEN 0 ELSE (SUM(SUBS_TOL) / SUM(SUBS_TOTAL)) * 100 END MKS_TOL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOT) = 0 THEN 0 ELSE (SUM(SUBS_TOT) / SUM(SUBS_TOTAL)) * 100 END MKS_TOT
	FROM W_BB_MKS_AGG_1
	WHERE PROVINCE_CD IN (10, 11, 12, 13) -->> 'Bangkok, Samut Prakan, Nonthaburi, Pathum Thani'
	GROUP BY TM_KEY_MTH, PROVINCE_CD, PROVINCE_ENG
	
	UNION ALL 
	
	-->> G : 8 Regional
	SELECT TM_KEY_MTH, 5 AS AREA_NO, 'G' AS AREA_TYPE, ORGID_G AS AREA_CD, TDS_SGMD AS AREA_NAME
		, SUM(SUBS_3BB) AS SUBS_3BB, SUM(SUBS_AIS) AS SUBS_AIS, SUM(SUBS_CAT) AS SUBS_CAT, SUM(SUBS_TOL) AS SUBS_TOL, SUM(SUBS_TOT) AS SUBS_TOT, SUM(SUBS_TOTAL) AS SUBS_TOTAL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_3BB) = 0 THEN 0 ELSE (SUM(SUBS_3BB) / SUM(SUBS_TOTAL)) * 100 END MKS_3BB
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_AIS) = 0 THEN 0 ELSE (SUM(SUBS_AIS) / SUM(SUBS_TOTAL)) * 100 END MKS_AIS
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_CAT) = 0 THEN 0 ELSE (SUM(SUBS_CAT) / SUM(SUBS_TOTAL)) * 100 END MKS_CAT
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOL) = 0 THEN 0 ELSE (SUM(SUBS_TOL) / SUM(SUBS_TOTAL)) * 100 END MKS_TOL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOT) = 0 THEN 0 ELSE (SUM(SUBS_TOT) / SUM(SUBS_TOTAL)) * 100 END MKS_TOT
	FROM W_BB_MKS_AGG_1
	GROUP BY TM_KEY_MTH, ORGID_G, TDS_SGMD
	
	UNION ALL 
	
	-->> H : 65 HOP_HINT
	SELECT TM_KEY_MTH, 6 AS AREA_NO, 'H' AS AREA_TYPE, ORGID_H AS AREA_CD, HOP_HINT AS AREA_NAME
		, SUM(SUBS_3BB) AS SUBS_3BB, SUM(SUBS_AIS) AS SUBS_AIS, SUM(SUBS_CAT) AS SUBS_CAT, SUM(SUBS_TOL) AS SUBS_TOL, SUM(SUBS_TOT) AS SUBS_TOT, SUM(SUBS_TOTAL) AS SUBS_TOTAL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_3BB) = 0 THEN 0 ELSE (SUM(SUBS_3BB) / SUM(SUBS_TOTAL)) * 100 END MKS_3BB
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_AIS) = 0 THEN 0 ELSE (SUM(SUBS_AIS) / SUM(SUBS_TOTAL)) * 100 END MKS_AIS
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_CAT) = 0 THEN 0 ELSE (SUM(SUBS_CAT) / SUM(SUBS_TOTAL)) * 100 END MKS_CAT
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOL) = 0 THEN 0 ELSE (SUM(SUBS_TOL) / SUM(SUBS_TOTAL)) * 100 END MKS_TOL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOT) = 0 THEN 0 ELSE (SUM(SUBS_TOT) / SUM(SUBS_TOTAL)) * 100 END MKS_TOT
	FROM W_BB_MKS_AGG_1
	GROUP BY TM_KEY_MTH, ORGID_H, HOP_HINT
	
	UNION ALL 
	
	-->> HH : 96 D_CLUSTER
	SELECT TM_KEY_MTH, 7 AS AREA_NO, 'HH' AS AREA_TYPE, ORGID_HH AS AREA_CD, D_CLUSTER AS AREA_NAME
		, SUM(SUBS_3BB) AS SUBS_3BB, SUM(SUBS_AIS) AS SUBS_AIS, SUM(SUBS_CAT) AS SUBS_CAT, SUM(SUBS_TOL) AS SUBS_TOL, SUM(SUBS_TOT) AS SUBS_TOT, SUM(SUBS_TOTAL) AS SUBS_TOTAL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_3BB) = 0 THEN 0 ELSE (SUM(SUBS_3BB) / SUM(SUBS_TOTAL)) * 100 END MKS_3BB
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_AIS) = 0 THEN 0 ELSE (SUM(SUBS_AIS) / SUM(SUBS_TOTAL)) * 100 END MKS_AIS
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_CAT) = 0 THEN 0 ELSE (SUM(SUBS_CAT) / SUM(SUBS_TOTAL)) * 100 END MKS_CAT
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOL) = 0 THEN 0 ELSE (SUM(SUBS_TOL) / SUM(SUBS_TOTAL)) * 100 END MKS_TOL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOT) = 0 THEN 0 ELSE (SUM(SUBS_TOT) / SUM(SUBS_TOTAL)) * 100 END MKS_TOT
	FROM W_BB_MKS_AGG_1
	GROUP BY TM_KEY_MTH, ORGID_HH, D_CLUSTER
	
	UNION ALL 
	
	-->> CCAA : 928 DISTRICT_UNIQUE
	SELECT TM_KEY_MTH, 8 AS AREA_NO, 'CCAA' AS AREA_TYPE, CCAA AS AREA_CD, DISTRICT_UNIQUE AS AREA_NAME
		, SUM(SUBS_3BB) AS SUBS_3BB, SUM(SUBS_AIS) AS SUBS_AIS, SUM(SUBS_CAT) AS SUBS_CAT, SUM(SUBS_TOL) AS SUBS_TOL, SUM(SUBS_TOT) AS SUBS_TOT, SUM(SUBS_TOTAL) AS SUBS_TOTAL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_3BB) = 0 THEN 0 ELSE (SUM(SUBS_3BB) / SUM(SUBS_TOTAL)) * 100 END MKS_3BB
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_AIS) = 0 THEN 0 ELSE (SUM(SUBS_AIS) / SUM(SUBS_TOTAL)) * 100 END MKS_AIS
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_CAT) = 0 THEN 0 ELSE (SUM(SUBS_CAT) / SUM(SUBS_TOTAL)) * 100 END MKS_CAT
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOL) = 0 THEN 0 ELSE (SUM(SUBS_TOL) / SUM(SUBS_TOTAL)) * 100 END MKS_TOL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOT) = 0 THEN 0 ELSE (SUM(SUBS_TOT) / SUM(SUBS_TOTAL)) * 100 END MKS_TOT
	FROM W_BB_MKS_AGG_1
	GROUP BY TM_KEY_MTH, CCAA, DISTRICT_UNIQUE
	
	UNION ALL 
	
	-->> CCAATT : 7,436 SUB_DISTRICT_EN
	SELECT TM_KEY_MTH, 9 AS AREA_NO, 'CCAATT' AS AREA_TYPE, CCAATT AS AREA_CD, SUB_DISTRICT_EN AS AREA_NAME
		, SUM(SUBS_3BB) AS SUBS_3BB, SUM(SUBS_AIS) AS SUBS_AIS, SUM(SUBS_CAT) AS SUBS_CAT, SUM(SUBS_TOL) AS SUBS_TOL, SUM(SUBS_TOT) AS SUBS_TOT, SUM(SUBS_TOTAL) AS SUBS_TOTAL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_3BB) = 0 THEN 0 ELSE (SUM(SUBS_3BB) / SUM(SUBS_TOTAL)) * 100 END MKS_3BB
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_AIS) = 0 THEN 0 ELSE (SUM(SUBS_AIS) / SUM(SUBS_TOTAL)) * 100 END MKS_AIS
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_CAT) = 0 THEN 0 ELSE (SUM(SUBS_CAT) / SUM(SUBS_TOTAL)) * 100 END MKS_CAT
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOL) = 0 THEN 0 ELSE (SUM(SUBS_TOL) / SUM(SUBS_TOTAL)) * 100 END MKS_TOL
		, CASE WHEN SUM(SUBS_TOTAL) = 0 OR SUM(SUBS_TOT) = 0 THEN 0 ELSE (SUM(SUBS_TOT) / SUM(SUBS_TOTAL)) * 100 END MKS_TOT
	FROM W_BB_MKS_AGG_1
	GROUP BY TM_KEY_MTH, CCAATT, SUB_DISTRICT_EN
	
) -->> W_BB_MKS_AGG_2
-----------------------------------------------------------------------------------------------------------------------

, W_RAW_BROADBAND_MKS_MONTHLY AS
(
	-->> VIN00019	Broadband Subs Share : AIS & 3BB
	SELECT TM_KEY_MTH, 'AIS & 3BB' AS OPERATOR, '%' AS UOM, 'VIN00019' AS METRIC_CD, 'Broadband Subs Share : AIS & 3BB' AS METRIC_NAME
		, AREA_NO, AREA_TYPE, AREA_CD, AREA_NAME
		, (MKS_AIS + MKS_3BB) AS METRIC_VALUE
	FROM W_BB_MKS_AGG_2
	
	UNION ALL 
	
	-->> VIN00020	Broadband Subs Share : TOL
	SELECT TM_KEY_MTH, 'TOL' AS OPERATOR, '%' AS UOM, 'VIN00020' AS METRIC_CD, 'Broadband Subs Share : TOL' AS METRIC_NAME
		, AREA_NO, AREA_TYPE, AREA_CD, AREA_NAME
		, MKS_TOL AS METRIC_VALUE
	FROM W_BB_MKS_AGG_2
	
	UNION ALL 
	
	-->> VIN00021	Broadband Subs Share : 3BB
	SELECT TM_KEY_MTH, '3BB' AS OPERATOR, '%' AS UOM, 'VIN00021' AS METRIC_CD, 'Broadband Subs Share : 3BB' AS METRIC_NAME
		, AREA_NO, AREA_TYPE, AREA_CD, AREA_NAME
		, MKS_3BB AS METRIC_VALUE
	FROM W_BB_MKS_AGG_2
	
	UNION ALL 
	
	-->> VIN00022	Broadband Subs Share : AIS
	SELECT TM_KEY_MTH, 'AIS' AS OPERATOR, '%' AS UOM, 'VIN00022' AS METRIC_CD, 'Broadband Subs Share : AIS' AS METRIC_NAME
		, AREA_NO, AREA_TYPE, AREA_CD, AREA_NAME
		, MKS_AIS AS METRIC_VALUE
	FROM W_BB_MKS_AGG_2
	
	UNION ALL 
	
	-->> VIN00023	Broadband Subs Share : NT
	SELECT TM_KEY_MTH, 'NT' AS OPERATOR, '%' AS UOM, 'VIN00023' AS METRIC_CD, 'Broadband Subs Share : NT' AS METRIC_NAME
		, AREA_NO, AREA_TYPE, AREA_CD, AREA_NAME
		, (MKS_CAT + MKS_TOT) AS METRIC_VALUE
	FROM W_BB_MKS_AGG_2

	UNION ALL 
	
	-->> VIN00024	Broadband Subs Share : AIS & 3BB
	SELECT TM_KEY_MTH, 'AIS & 3BB' AS OPERATOR, 'subs' AS UOM, 'VIN00024' AS METRIC_CD, 'Broadband Subs Share (Subs) : AIS & 3BB' AS METRIC_NAME
		, AREA_NO, AREA_TYPE, AREA_CD, AREA_NAME
		, (SUBS_AIS + SUBS_3BB) AS METRIC_VALUE
	FROM W_BB_MKS_AGG_2
	
	UNION ALL 
	
	-->> VIN00025	Broadband Subs Share : TOL
	SELECT TM_KEY_MTH, 'TOL' AS OPERATOR, 'subs' AS UOM, 'VIN00025' AS METRIC_CD, 'Broadband Subs Share (Subs) : TOL' AS METRIC_NAME
		, AREA_NO, AREA_TYPE, AREA_CD, AREA_NAME
		, SUBS_TOL AS METRIC_VALUE
	FROM W_BB_MKS_AGG_2
	
	UNION ALL 
	
	-->> VIN00026	Broadband Subs Share : 3BB
	SELECT TM_KEY_MTH, '3BB' AS OPERATOR, 'subs' AS UOM, 'VIN00026' AS METRIC_CD, 'Broadband Subs Share (Subs) : 3BB' AS METRIC_NAME
		, AREA_NO, AREA_TYPE, AREA_CD, AREA_NAME
		, SUBS_3BB AS METRIC_VALUE
	FROM W_BB_MKS_AGG_2
	
	UNION ALL 
	
	-->> VIN00027	Broadband Subs Share : AIS
	SELECT TM_KEY_MTH, 'AIS' AS OPERATOR, 'subs' AS UOM, 'VIN00027' AS METRIC_CD, 'Broadband Subs Share (Subs) : AIS' AS METRIC_NAME
		, AREA_NO, AREA_TYPE, AREA_CD, AREA_NAME
		, SUBS_AIS AS METRIC_VALUE
	FROM W_BB_MKS_AGG_2
	
	UNION ALL 
	
	-->> VIN00028	Broadband Subs Share : NT
	SELECT TM_KEY_MTH, 'NT' AS OPERATOR, 'subs' AS UOM, 'VIN00028' AS METRIC_CD, 'Broadband Subs Share (Subs) : NT' AS METRIC_NAME
		, AREA_NO, AREA_TYPE, AREA_CD, AREA_NAME
		, (SUBS_CAT + SUBS_TOT) AS METRIC_VALUE
	FROM W_BB_MKS_AGG_2

) -->> W_RAW_BROADBAND_MKS_MONTHLY
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


-->> Output to "AUTOKPI.FCT_BROADBAND_MKS"

SELECT *
FROM (
	-->> Initial data
	SELECT P.TM_KEY_YR, P.TM_KEY_MTH, P.TRUE_TM_KEY_WK, P.TM_KEY_DAY
		, A.METRIC_CD, A.METRIC_NAME
		, 'TRUE' AS COMP_CD, 'A' AS VERSION
		, A.AREA_NO, A.AREA_TYPE, A.AREA_CD, A.AREA_NAME, A.METRIC_VALUE
		, 'N' AS AGG_TYPE, 'Monthly' AS FREQUENCY, NULL AS REMARK
	FROM W_RAW_BROADBAND_MKS_MONTHLY A
	LEFT JOIN CDSAPPO.DIM_TIME P
		ON P.TM_KEY_MTH = A.TM_KEY_MTH
) FCT_BROADBAND_MKS
ORDER BY TM_KEY_DAY, METRIC_CD, AREA_NO, AREA_CD
;

-->> Test
-- WHERE METRIC_CD = 'VIN00020'
-- AND AREA_CD = 'P'