

/*** Rawdata : Broadband MKS by 77 Province ***/

-----------------------------------------------------------------------------------------------------------------------

WITH W_PARAM_PERIOD AS 
(
	SELECT TM_KEY_DAY AS END_OF_LAST_MTH
	FROM GEOSPCAPPO.DIM_TIME_CITRINE
	WHERE PERIODFLAG IN ('EM', 'EMQ', 'EMQY')
	AND TM_KEY_MTH = TO_CHAR(ADD_MONTHS(CURRENT_DATE, -1), 'YYYYMM') -->> Automate Last MONTH
	--AND TM_KEY_MTH BETWEEN 202501 AND 202504 -->> Initial Period
)
-----------------------------------------------------------------------------------------------------------------------

, W_BROADBAND_SUBS_RAWDATA AS 
(
	SELECT SUBSTR(TM_KEY_DAY,1,4) AS TM_KEY_YR, SUBSTR(TM_KEY_DAY,1,6) AS TM_KEY_MTH, 'Broadband' AS PRODUCT
		, O.PROVINCE_CD, O.PROVINCE_ENG, O.PROVINCE_TH 
		, SUM(CASE WHEN METRIC_CD = 'VIN00086' THEN ACTUAL_AGG_MTH END) SUBS_TOL
		, SUM(CASE WHEN METRIC_CD = 'VIN00085' THEN ACTUAL_AGG_MTH END) "SUBS_AIS & 3BB"
		, SUM(CASE WHEN METRIC_CD = 'VIN00087' THEN ACTUAL_AGG_MTH END) SUBS_3BB
		, SUM(CASE WHEN METRIC_CD = 'VIN00088' THEN ACTUAL_AGG_MTH END) SUBS_AIS
		, SUM(CASE WHEN METRIC_CD = 'VIN00089' THEN ACTUAL_AGG_MTH END) SUBS_NT
		, SUM(CASE WHEN METRIC_CD IN ('VIN00086', 'VIN00087', 'VIN00088', 'VIN00089') THEN ACTUAL_AGG_MTH END) SUBS_TOTAL
		
	FROM GEOSPCAPPO.AGG_PERF_NEWCO A
	
	INNER JOIN W_PARAM_PERIOD P
		ON P.END_OF_LAST_MTH = A.TM_KEY_DAY
		AND A.METRIC_CD IN (
			'VIN00085' --Broadband Subs Share (Subs) : AIS & 3BB
			, 'VIN00086' --Broadband Subs Share (Subs) : TOL
			, 'VIN00087' --Broadband Subs Share (Subs) : 3BB
			, 'VIN00088' --Broadband Subs Share (Subs) : AIS
			, 'VIN00089' --Broadband Subs Share (Subs) : NT
			) 
		AND A.AREA_TYPE = 'HH'
		
	INNER JOIN (
		SELECT DISTINCT ORGID_HH, D_CLUSTER
			, SUBSTR(CCAATT,1,2) AS PROVINCE_CD, PROVINCE_ENG, PROVINCE_TH
		FROM CDSAPPO.DIM_MOOC_AREA
		WHERE TEAM_CODE <> 'ไม่ระบุ' AND REMARK <> 'Dummy'
	) O
		ON O.ORGID_HH = A.AREA_CD
		
	GROUP BY TM_KEY_DAY, O.PROVINCE_CD, O.PROVINCE_ENG, O.PROVINCE_TH 
)
-----------------------------------------------------------------------------------------------------------------------


/* Rawdata Output */

SELECT TM_KEY_YR, TM_KEY_MTH, PRODUCT, PROVINCE_CD, PROVINCE_ENG, PROVINCE_TH
	-->> %MKS
	, SUBS_TOL / SUBS_TOTAL * 100 AS MKS_TOL
	, "SUBS_AIS & 3BB" / SUBS_TOTAL * 100 AS "MKS_AIS & 3BB"
	, SUBS_3BB / SUBS_TOTAL * 100 AS MKS_3BB
	, SUBS_AIS / SUBS_TOTAL * 100 AS MKS_AIS
	, SUBS_NT / SUBS_TOTAL * 100 AS MKS_NT
	-->> Subs
	, SUBS_TOL, "SUBS_AIS & 3BB", SUBS_3BB, SUBS_AIS, SUBS_NT, SUBS_TOTAL
	, CURRENT_DATE AS LOAD_DATE
FROM W_BROADBAND_SUBS_RAWDATA
ORDER BY TM_KEY_MTH, PROVINCE_CD
