
/*** Import : "CDSAPPO.DIM_TIME" to "dim_time.csv" ***/

-----------------------------------------------------------------------------------------------------------------------

WITH W_PARAM AS 
(
	SELECT :yr_start AS V_YR_START
		, :yr_end AS V_YR_END
	FROM DUAL
)
-----------------------------------------------------------------------------------------------------------------------

-- SELECT TM_KEY_DAY, DAY_DESC, DAY_SHORT, DAY_NO, DATE_VALUE, DAY_OF_WEEK, DAYS_IN_MONTH, TRUE_TM_KEY_WK, TRUE_WEEK, TM_KEY_WK, WEEK_YEAR, TM_KEY_MTH, MONTH_NO, MONTH_SHORT, TM_KEY_QTR, QUARTER_NO, TM_KEY_YR, YEAR_DESC, YEAR_DESC_TH
-- 	, PERIODFLAG, ETL_DATE, ETL_UPDATE 
-- 	, CURRENT_DATE AS LOAD_DATE

SELECT TM_KEY_DAY, DATE_ID, DATE_VALUE, DATE_DESC, DAY_DESC, DAY_SHORT, DAY_DESC_TH, DAY_SHORT_TH, DAY_NO, DAY_OF_WEEK, DAYS_IN_MONTH, TM_KEY_WK, WEEK_DESC, WEEK_YEAR, TRUE_TM_KEY_WK, TRUE_WEEK, TRUE_WEEK_DESC, TM_KEY_MTH, MONTH_ID, MONTH_SHORT, MONTH_DESC, MONTH_SHORT_TH, MONTH_DESC_TH, MONTH_NO, MONTH_BEG_DATE, MONTH_END_DATE, TM_KEY_QTR, QUARTER_DESC, QUARTER_SHORT, QUARTER_DESC_TH, QUARTER_SHORT_TH, QUARTER_NO, TM_KEY_YR, YEAR_DESC, YEAR_SHORT, YEAR_DESC_TH, YEAR_SHORT_TH, PERIODFLAG, ETL_DATE, ETL_UPDATE, WEEK_MONTH, WEEK_MONTH_DESC, TRUE_WK_BEG_DATE, TRUE_WK_END_DATE, TRUE_WK_MTH_BEG_DATE, TRUE_WK_MTH_END_DATE
FROM CDSAPPO.DIM_TIME 
WHERE TM_KEY_YR >= (SELECT V_YR_START FROM W_PARAM)
ORDER BY TM_KEY_DAY 
;