
/***
 	Aggregate : Prepaid GA ARPU by channel 36 KPIs (All area)
	
	ALL : 12 KPIs(All Channel)
		B1R001200	Prepaid GA ARPU = ("B1R000900 Prepaid Inflow M1" / "B1S000101 Prepaid Gross Adds")
		
	DTAC : 12 KPIs(All Channel)
		DB1R001200	Prepaid GA ARPU : DTAC = ("DB1R000900 Prepaid Inflow M1 : DTAC" / "DB1S000101 Prepaid Gross Adds : DTAC")
		
	TRUE : 12 KPIs(All Channel)
		TB1R001200	Prepaid GA ARPU : TMH = ("TB1R000900 Prepaid Inflow M1 : TMH" / "TB1S000101 Prepaid Gross Adds : TMH")
***/
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/*** Temp Parameter ***/

WITH W_PARAM AS
(
	SELECT 2024 AS TM_KEY_YR FROM DUAL
)
-->> fetched - about 3-5 min.
-----------------------------------------------------------------------------------------------------------------------


/** Aggregate Sctips ***/


SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
	, CURRENT_DATE AS LOAD_DATE, REMARK
	
FROM ( 
	
	-->> B1R001200 Prepaid GA ARPU = ("B1R000900 Prepaid Inflow M1" / "B1S000101 Prepaid Gross Adds")
	SELECT M1.TM_KEY_DAY
		, REPLACE(M1.METRIC_CD, 'B1R000900', 'B1R001200') AS METRIC_CD
		, REPLACE(M1.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
		, CASE WHEN COALESCE(GA.ACTUAL_AGG,0) <> 0 THEN (M1.ACTUAL_AGG / GA.ACTUAL_AGG) * 100 END METRIC_VALUE -->> Calculation
		, 'ALL' AS COMP_CD, 'A' AS VERSION, M1.AREA_CD, M1.AREA_NAME, M1.AREA_TYPE
		, M1.METRIC_CD||' '||M1.METRIC_NAME||' / '||GA.METRIC_CD||' '||GA.METRIC_NAME AS REMARK
		
	FROM ( -->> B1R000900xx Prepaid Inflow M1 (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'B1R000900' OR REGEXP_LIKE(METRIC_CD, '^B1R000900A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1
	
	LEFT JOIN ( -->> B1S000101xx Prepaid Gross Adds (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'B1S000101' OR REGEXP_LIKE(METRIC_CD, '^B1S000101A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA
		ON M1.CHANNEL_CD = GA.CHANNEL_CD
		AND M1.AREA_CD = GA.AREA_CD
		AND M1.TM_KEY_DAY = GA.TM_KEY_DAY
	-----------------------------------------------------------------------------------------------------------------------
		
	UNION ALL 

	-->> DB1R001200 Prepaid GA ARPU : DTAC = ("DB1R000900 Prepaid Inflow M1 : DTAC" / "DB1S000101 Prepaid Gross Adds : DTAC")
	SELECT M1_D.TM_KEY_DAY
		, REPLACE(M1_D.METRIC_CD, 'DB1R000900', 'DB1R001200') AS METRIC_CD
		, REPLACE(M1_D.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
		, CASE WHEN COALESCE(GA_D.ACTUAL_AGG,0) <> 0 THEN (M1_D.ACTUAL_AGG / GA_D.ACTUAL_AGG) * 100 END METRIC_VALUE -->> Calculation
		, 'DTAC' AS COMP_CD, 'A' AS VERSION, M1_D.AREA_CD, M1_D.AREA_NAME, M1_D.AREA_TYPE
		, M1_D.METRIC_CD||' '||M1_D.METRIC_NAME||' / '||GA_D.METRIC_CD||' '||GA_D.METRIC_NAME AS REMARK
		
	FROM ( -->> DB1R000900xx Prepaid Inflow M1 : DTAC (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'DB1R000900' OR REGEXP_LIKE(METRIC_CD, '^DB1R000900A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1_D
	
	LEFT JOIN ( -->> DB1S000101xx Prepaid Gross Adds : DTAC (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'DB1S000101' OR REGEXP_LIKE(METRIC_CD, '^DB1S000101A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA_D
		ON M1_D.CHANNEL_CD = GA_D.CHANNEL_CD
		AND M1_D.AREA_CD = GA_D.AREA_CD
		AND M1_D.TM_KEY_DAY = GA_D.TM_KEY_DAY
	-----------------------------------------------------------------------------------------------------------------------
		
	UNION ALL 
	
	-->> TB1R001200 Prepaid GA ARPU : TMH = ("TB1R000900 Prepaid Inflow M1 : TMH" / "TB1S000101 Prepaid Gross Adds : TMH")
	SELECT M1_T.TM_KEY_DAY
		, REPLACE(M1_T.METRIC_CD, 'TB1R000900', 'TB1R001200') AS METRIC_CD
		, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
		, CASE WHEN COALESCE(GA_T.ACTUAL_AGG,0) <> 0 THEN (M1_T.ACTUAL_AGG / GA_T.ACTUAL_AGG) * 100 END METRIC_VALUE -->> Calculation
		, 'TRUE' AS COMP_CD, 'A' AS VERSION, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
		, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
		
	FROM ( -->> TB1R000900xx Prepaid Inflow M1 : TMH (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB1R000900' OR REGEXP_LIKE(METRIC_CD, '^TB1R000900A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) M1_T
	
	LEFT JOIN ( -->> TB1S000101xx Prepaid Gross Adds : TMH (by Channel)
		SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG
			, CASE WHEN REGEXP_LIKE(SUBSTR(METRIC_CD,-2), 'A[A-K]$') THEN SUBSTR(METRIC_CD,-2) ELSE 'ALL' END CHANNEL_CD
		FROM GEOSPCAPPO.AGG_PERF_NEWCO 
		WHERE (METRIC_CD = 'TB1S000101' OR REGEXP_LIKE(METRIC_CD, '^TB1S000101A[A-K]$')) 
		AND TM_KEY_YR >= (SELECT TM_KEY_YR FROM W_PARAM)
	) GA_T
		ON M1_T.CHANNEL_CD = GA_T.CHANNEL_CD
		AND M1_T.AREA_CD = GA_T.AREA_CD
		AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
		
) PREPAID_GA_ARPU_BY_CHANNEL
