CREATE OR REPLACE PROCEDURE GEOSPCAPPO.PRC_FCT_KPI_NEWCO_COMMON_KPI (DATA_AS_OF_DAY  VARCHAR2) AS 

/* ================================================================= */
/* Created date   : 10-Feb-2025                                      */
/* Created by     : Krawin P.                                        */
/* Objective      : Support Sales KPIs (Conversion, GA ARPU/RC)      */
/* ================================================================= */
/* Modified date  :                                                  */
/* Modified by    :                                                  */
/* ================================================================= */

--V_SNAP_TM_KEY NUMBER := TO_NUMBER(DATA_AS_OF_DAY) ;
--V_TM_YEAR     NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),1,4)) ;
--V_TM_MONTH    NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),1,6)) ;
--V_TM_DATE     NUMBER := TO_NUMBER(SUBSTR(TRIM(DATA_AS_OF_DAY),7,2)) ;
V_SNAP_TM_KEY NUMBER := TO_NUMBER(20231224) ;


BEGIN

EXECUTE IMMEDIATE 'TRUNCATE TABLE GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL';
COMMIT;

-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------

/***
Aggregate Scripts : GA ARPU/RC & Conversion M2 to M1 : 22 KPIs (C, P, G, H, HH)
	
	
	GA ARPU/RC : : 16 KPIs
	
		TOL : 	
			TB3R000800CS TOL GA ARPU
			TB3R000800CG TOL GA ARPU - GEO Channel
		
		TVS : 	
			TB4R001800CS TVS Now GA ARPU
			TB4R001800CG TVS Now GA ARPU - GEO Channel
		
		PREPAID : 
			B1R001200CS Prepaid GA ARPU
			B1R001200CG Prepaid GA ARPU - GEO Channel
			DB1R001200CS Prepaid GA ARPU : DTAC
			DB1R001200CG Prepaid GA ARPU : DTAC - GEO Channel
			TB1R001200CS Prepaid GA ARPU : TMH
			TB1R001200CG Prepaid GA ARPU : TMH - GEO Channel 
			
		POSTPAID : 
			B2R010600CS Postpaid GA RC B2C
			B2R010600CG Postpaid GA RC B2C - GEO Channel
			DB2R010600CS Postpaid GA RC B2C : DTAC
			DB2R010600CG Postpaid GA RC : DTAC - GEO Channel
			TB2R010600CS Postpaid GA RC B2C : TMH
			TB2R010600CG Postpaid GA RC : TMH - GEO Channel
						
								
	Conversion M2 to M1 : 6 KPIs
			
		PREPAID : 
			B1R001100CS Prepaid Conversion M2 to M1
			B1R001100CG Prepaid Conversion M2 to M1 - GEO Channel
			DB1R001100CS Prepaid Conversion M2 to M1 : DTAC
			DB1R001100CG Prepaid Conversion M2 to M1 : DTAC - GEO Channel
			TB1R001100CS Prepaid Conversion M2 to M1 : TMH
			TB1R001100CG Prepaid Conversion M2 to M1 : TMH - GEO Channel
			

	Revenue Growth (YTD YoY%) : 4 KPIs
	
		B0R0001001GEO	Total Service Revenue Growth (YTD YoY%)
		B0R0001004	Prepaid Revenue Growth (YTD YoY%)
		B0R0101003	Postpaid Revenue Growth B2C (YTD YoY%)
		B0R0001005	TOL Revenue Growth (YTD YoY%)
***/
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/* TVS_NOW_GA_ARPU */

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM ( 
		-->> All Channel : TB4R001800CS TVS Now GA ARPU = ("TB4R001700CS TVS Now Inflow M1" / "TB4S001400CS TVS Now Gross Adds")
		SELECT M1_T.TM_KEY_DAY
			, REPLACE(M1_T.METRIC_CD, 'TB4R001700CS', 'TB4R001800CS') AS METRIC_CD
			, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
			, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
			, 'TRUE' AS COMP_CD, 'A' AS VERSION
			, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
			, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
		FROM ( -->> TB4R001700CS TVS Now Inflow M1
			SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'TB4R001700CS' 
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= V_SNAP_TM_KEY
		) M1_T
		LEFT JOIN ( -->> TB4S001400CS TVS Now Gross Adds
			SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'TB4S001400CS'
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= V_SNAP_TM_KEY
		) GA_T
			ON M1_T.AREA_CD = GA_T.AREA_CD
			AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
	) TVS_NOW_GA_ARPU
	;

COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM ( 
		
		-->> GEO Channel : TB4R001800CG TVS Now GA ARPU - GEO Channel = ("TB4R001700CG TVS Now Inflow M1 - GEO Channel" / "TB4S001400CG TVS Now Gross Adds - GEO Channel")
		SELECT M1_T.TM_KEY_DAY
			, REPLACE(M1_T.METRIC_CD, 'TB4R001700CG', 'TB4R001800CG') AS METRIC_CD
			, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
			, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
			, 'TRUE' AS COMP_CD, 'A' AS VERSION
			, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
			, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
		FROM ( -->> TB4R001700CG TVS Now Inflow M1 - GEO Channel
			SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'TB4R001700CG' 
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= V_SNAP_TM_KEY
		) M1_T
		LEFT JOIN ( -->> TB4S001400CG TVS Now Gross Adds - GEO Channel
			SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'TB4S001400CG'
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= V_SNAP_TM_KEY
		) GA_T
			ON M1_T.AREA_CD = GA_T.AREA_CD
			AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
	) TVS_NOW_GA_ARPU
	;

COMMIT;
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/* TOL_GA_ARPU */

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
	
	FROM (
		-->> All Channel : TB3R000800CS TOL GA ARPU = ("TB3R000601CS TOL Inflow M1 Connected : Consumer" / "TB3S000102CS TOL Gross Adds Connected : Consumer")
		SELECT M1_T.TM_KEY_DAY
			, REPLACE(M1_T.METRIC_CD, 'TB3R000601CS', 'TB3R000800CS') AS METRIC_CD
			, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
			, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
			, 'TRUE' AS COMP_CD, 'A' AS VERSION
			, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
			, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
		FROM ( -->> TB3R000601CS TOL Inflow M1 Connected : Consumer
			SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'TB3R000601CS'
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= V_SNAP_TM_KEY
		) M1_T
		LEFT JOIN ( -->> TB3S000102CS TOL Gross Adds Connected : Consumer
			SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'TB3S000102CS'
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= V_SNAP_TM_KEY
		) GA_T
			ON M1_T.AREA_CD = GA_T.AREA_CD
			AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
	) TOL_GA_ARPU
	;
	
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
	
	FROM (
		
		-->> GEO Channel : TB3R000800CG TOL GA ARPU - GEO Channel = ("TB3R000601CG TOL Inflow M1 Connected : Consumer - GEO Channel" / "TB3S000102CG TOL Gross Adds Connected : Consumer - GEO Channel")
		SELECT M1_T.TM_KEY_DAY
			, REPLACE(M1_T.METRIC_CD, 'TB3R000601CG', 'TB3R000800CG') AS METRIC_CD
			, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
			, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
			, 'TRUE' AS COMP_CD, 'A' AS VERSION
			, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
			, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
		FROM ( -->> TB3R000601CG TOL Inflow M1 Connected : Consumer - GEO Channel
			SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'TB3R000601CG'
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= V_SNAP_TM_KEY
		) M1_T
		LEFT JOIN ( -->> TB3S000102CG TOL Gross Adds Connected : Consumer - GEO Channel
			SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'TB3S000102CG'
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= V_SNAP_TM_KEY
		) GA_T
			ON M1_T.AREA_CD = GA_T.AREA_CD
			AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
	) TOL_GA_ARPU
	;
	
COMMIT;
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/* POSTPAID_B2C_GA_RC */

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
	
		-->> All Channel
			-->> ALL : B2R010600CS Postpaid GA RC B2C = ("B2R010500CS Postpaid Inflow M1 B2C" / "B2S010100CS Postpaid Gross Adds B2C")
			SELECT M1.TM_KEY_DAY
				, REPLACE(M1.METRIC_CD, 'B2R010500CS', 'B2R010600CS') AS METRIC_CD
				, REPLACE(M1.METRIC_NAME, 'Inflow M1', 'GA RC') AS METRIC_NAME
				, CASE WHEN COALESCE(GA.ACTUAL_AGG_MTH,0) <> 0 THEN (M1.ACTUAL_AGG_MTH / GA.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'ALL' AS COMP_CD, 'A' AS VERSION
				, M1.AREA_CD, M1.AREA_NAME, M1.AREA_TYPE
				, M1.METRIC_CD||' '||M1.METRIC_NAME||' / '||GA.METRIC_CD||' '||GA.METRIC_NAME AS REMARK
			FROM ( -->> B2R010500CS Postpaid Inflow M1 B2C
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B2R010500CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1
			LEFT JOIN ( -->> B2S010100CS Postpaid Gross Adds B2C
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B2S010100CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA
				ON M1.AREA_CD = GA.AREA_CD
				AND M1.TM_KEY_DAY = GA.TM_KEY_DAY
			
			) POSTPAID_B2C_GA_RC_ALL_CHNL
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
			-->> DTAC : DB2R010600CS Postpaid GA RC B2C : DTAC = ("DB2R010500CS Postpaid Inflow M1 B2C : DTAC" / "DB2S010100CS Postpaid Gross Adds B2C : DTAC")
			SELECT M1_D.TM_KEY_DAY
				, REPLACE(M1_D.METRIC_CD, 'DB2R010500CS', 'DB2R010600CS') AS METRIC_CD
				, REPLACE(M1_D.METRIC_NAME, 'Inflow M1', 'GA RC') AS METRIC_NAME
				, CASE WHEN COALESCE(GA_D.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_D.ACTUAL_AGG_MTH / GA_D.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'DTAC' AS COMP_CD, 'A' AS VERSION
				, M1_D.AREA_CD, M1_D.AREA_NAME, M1_D.AREA_TYPE
				, M1_D.METRIC_CD||' '||M1_D.METRIC_NAME||' / '||GA_D.METRIC_CD||' '||GA_D.METRIC_NAME AS REMARK
			FROM ( -->> DB2R010500CS Postpaid Inflow M1 B2C : DTAC
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB2R010500CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1_D
			LEFT JOIN ( -->> DB2S010100CS Postpaid Gross Adds B2C : DTAC
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB2S010100CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA_D
				ON M1_D.AREA_CD = GA_D.AREA_CD
				AND M1_D.TM_KEY_DAY = GA_D.TM_KEY_DAY
				
			) POSTPAID_B2C_GA_RC_ALL_CHNL
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
			
			-->> TRUE : TB2R010600CS Postpaid GA RC B2C : TMH = ("TB2R010500CS Postpaid Inflow M1 B2C : TMH" / "TB2S010100CS Postpaid Gross Adds B2C : TMH")
			SELECT M1_T.TM_KEY_DAY
				, REPLACE(M1_T.METRIC_CD, 'TB2R010500CS', 'TB2R010600CS') AS METRIC_CD
				, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA RC') AS METRIC_NAME
				, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'TRUE' AS COMP_CD, 'A' AS VERSION
				, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
				, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
			FROM ( -->> TB2R010500CS Postpaid Inflow M1 B2C : TMH
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB2R010500CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1_T
			
			LEFT JOIN ( -->> TB2S010100CS Postpaid Gross Adds B2C : TMH
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB2S010100CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA_T
				ON M1_T.AREA_CD = GA_T.AREA_CD
				AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
		) POSTPAID_B2C_GA_RC_ALL_CHNL
		-----------------------------------------------------------------------------------------------------------------------

;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
	
		-->> GEO Channel
			-->> ALL(Geo) : B2R010600CG Postpaid GA RC B2C - GEO Channel = ("B2R010500CG Postpaid Inflow M1 B2C - GEO Channel" / "B2S010100CG Postpaid Gross Adds B2C - GEO Channel")
			SELECT M1.TM_KEY_DAY
				, REPLACE(M1.METRIC_CD, 'B2R010500CG', 'B2R010600CG') AS METRIC_CD
				, REPLACE(M1.METRIC_NAME, 'Inflow M1', 'GA RC') AS METRIC_NAME
				, CASE WHEN COALESCE(GA.ACTUAL_AGG_MTH,0) <> 0 THEN (M1.ACTUAL_AGG_MTH / GA.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'ALL' AS COMP_CD, 'A' AS VERSION
				, M1.AREA_CD, M1.AREA_NAME, M1.AREA_TYPE
				, M1.METRIC_CD||' '||M1.METRIC_NAME||' / '||GA.METRIC_CD||' '||GA.METRIC_NAME AS REMARK
			FROM ( -->> B2R010500CG Postpaid Inflow M1 B2C - GEO Channel
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B2R010500CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1
			LEFT JOIN ( -->> B2S010100CG Postpaid Gross Adds B2C - GEO Channel
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B2S010100CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA
				ON M1.AREA_CD = GA.AREA_CD
				AND M1.TM_KEY_DAY = GA.TM_KEY_DAY
			
			) POSTPAID_B2C_GA_RC_ALL_CHNL
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
			
			-->> DTAC(Geo) : DB2R010600CG Postpaid GA RC : DTAC - GEO Channel = ("DB2R010500CG Postpaid Inflow M1 B2C : DTAC - GEO Channel" / "DB2S010100CG Postpaid Gross Adds B2C : DTAC - GEO Channel")
			SELECT M1_D.TM_KEY_DAY
				, REPLACE(M1_D.METRIC_CD, 'DB2R010500CG', 'DB2R010600CG') AS METRIC_CD
				, REPLACE(M1_D.METRIC_NAME, 'Inflow M1', 'GA RC') AS METRIC_NAME
				, CASE WHEN COALESCE(GA_D.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_D.ACTUAL_AGG_MTH / GA_D.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'DTAC' AS COMP_CD, 'A' AS VERSION
				, M1_D.AREA_CD, M1_D.AREA_NAME, M1_D.AREA_TYPE
				, M1_D.METRIC_CD||' '||M1_D.METRIC_NAME||' / '||GA_D.METRIC_CD||' '||GA_D.METRIC_NAME AS REMARK
			FROM ( -->> DB2R010500CG Postpaid Inflow M1 B2C : DTAC - GEO Channel
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB2R010500CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1_D
			LEFT JOIN ( -->> DB2S010100CG Postpaid Gross Adds B2C : DTAC - GEO Channel
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB2S010100CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA_D
				ON M1_D.AREA_CD = GA_D.AREA_CD
				AND M1_D.TM_KEY_DAY = GA_D.TM_KEY_DAY
				
			) POSTPAID_B2C_GA_RC_ALL_CHNL
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
			
			-->> TRUE(Geo) : TB2R010600CG Postpaid GA RC : TMH - GEO Channel = ("TB2R010500CG Postpaid Inflow M1 B2C : TMH - GEO Channel" / "TB2S010100CG Postpaid Gross Adds B2C : TMH - GEO Channel")
			SELECT M1_T.TM_KEY_DAY
				, REPLACE(M1_T.METRIC_CD, 'TB2R010500CG', 'TB2R010600CG') AS METRIC_CD
				, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA RC') AS METRIC_NAME
				, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'TRUE' AS COMP_CD, 'A' AS VERSION
				, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
				, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
			FROM ( -->> TB2R010500CG Postpaid Inflow M1 B2C : TMH - GEO Channel
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB2R010500CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1_T
			LEFT JOIN ( -->> TB2S010100CG Postpaid Gross Adds B2C : TMH - GEO Channel
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB2S010100CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA_T
				ON M1_T.AREA_CD = GA_T.AREA_CD
				AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
		) POSTPAID_B2C_GA_RC_GEO_CHNL
	;

COMMIT;
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/* PREPAID_GA_ARPU */

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
	
		-->> All Channel
		
			-->> ALL : B1R001200CS Prepaid GA ARPU = ("B1R000900CS Prepaid Inflow M1" / "B1S000101CS Prepaid Gross Adds")
			SELECT M1.TM_KEY_DAY
				, REPLACE(M1.METRIC_CD, 'B1R000900CS', 'B1R001200CS') AS METRIC_CD
				, REPLACE(M1.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
				, CASE WHEN COALESCE(GA.ACTUAL_AGG_MTH,0) <> 0 THEN (M1.ACTUAL_AGG_MTH / GA.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'ALL' AS COMP_CD, 'A' AS VERSION
				, M1.AREA_CD, M1.AREA_NAME, M1.AREA_TYPE
				, M1.METRIC_CD||' '||M1.METRIC_NAME||' / '||GA.METRIC_CD||' '||GA.METRIC_NAME AS REMARK
			FROM ( -->> B1R000900CS Prepaid Inflow M1
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B1R000900CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1
			LEFT JOIN ( -->> B1S000101CS Prepaid Gross Adds
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B1S000101CS' 
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA
				ON M1.AREA_CD = GA.AREA_CD
				AND M1.TM_KEY_DAY = GA.TM_KEY_DAY
				
			) PREPAID_GA_ARPU_ALL_CHNL
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
		
			-->> DTAC : DB1R001200CS Prepaid GA ARPU : DTAC = ("DB1R000900CS Prepaid Inflow M1 : DTAC" / "DB1S000101CS Prepaid Gross Adds : DTAC")
			SELECT M1_D.TM_KEY_DAY
				, REPLACE(M1_D.METRIC_CD, 'DB1R000900CS', 'DB1R001200CS') AS METRIC_CD
				, REPLACE(M1_D.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
				, CASE WHEN COALESCE(GA_D.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_D.ACTUAL_AGG_MTH / GA_D.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'DTAC' AS COMP_CD, 'A' AS VERSION
				, M1_D.AREA_CD, M1_D.AREA_NAME, M1_D.AREA_TYPE
				, M1_D.METRIC_CD||' '||M1_D.METRIC_NAME||' / '||GA_D.METRIC_CD||' '||GA_D.METRIC_NAME AS REMARK
			FROM ( -->> DB1R000900CS Prepaid Inflow M1 : DTAC
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB1R000900CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1_D
			LEFT JOIN ( -->> DB1S000101CS Prepaid Gross Adds : DTAC
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB1S000101CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA_D
				ON M1_D.AREA_CD = GA_D.AREA_CD
				AND M1_D.TM_KEY_DAY = GA_D.TM_KEY_DAY
				
			) PREPAID_GA_ARPU_ALL_CHNL
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
		
			-->> TRUE : TB1R001200CS Prepaid GA ARPU : TMH = ("TB1R000900CS Prepaid Inflow M1 : TMH" / "TB1S000101CS Prepaid Gross Adds : TMH")
			SELECT M1_T.TM_KEY_DAY
				, REPLACE(M1_T.METRIC_CD, 'TB1R000900CS', 'TB1R001200CS') AS METRIC_CD
				, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
				, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'TRUE' AS COMP_CD, 'A' AS VERSION
				, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
				, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
			FROM ( -->> TB1R000900CS Prepaid Inflow M1 : TMH
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB1R000900CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1_T
			LEFT JOIN ( -->> TB1S000101CS Prepaid Gross Adds : TMH
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB1S000101CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA_T
				ON M1_T.AREA_CD = GA_T.AREA_CD
				AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
		) PREPAID_GA_ARPU_ALL_CHNL
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
		-----------------------------------------------------------------------------------------------------------------------

	
		-->> GEO Channel

			-->> ALL(Geo) : B1R001200CG Prepaid GA ARPU - GEO Channel = ("B1R000900CG Prepaid Inflow M1 - GEO Channel" / "B1S000101CG Prepaid Gross Adds - GEO Channel")
			SELECT M1.TM_KEY_DAY
				, REPLACE(M1.METRIC_CD, 'B1R000900CG', 'B1R001200CG') AS METRIC_CD
				, REPLACE(M1.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
				, CASE WHEN COALESCE(GA.ACTUAL_AGG_MTH,0) <> 0 THEN (M1.ACTUAL_AGG_MTH / GA.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'ALL' AS COMP_CD, 'A' AS VERSION
				, M1.AREA_CD, M1.AREA_NAME, M1.AREA_TYPE
				, M1.METRIC_CD||' '||M1.METRIC_NAME||' / '||GA.METRIC_CD||' '||GA.METRIC_NAME AS REMARK
			FROM ( -->> B1R000900CG Prepaid Inflow M1 - GEO Channel
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B1R000900CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1
			LEFT JOIN ( -->> B1S000101CG Prepaid Gross Adds - GEO Channel
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B1S000101CG' 
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA
				ON M1.AREA_CD = GA.AREA_CD
				AND M1.TM_KEY_DAY = GA.TM_KEY_DAY
				
		) PREPAID_GA_ARPU_ALL_CHNL
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
		
			-->> DTAC(Geo) : DB1R001200CG Prepaid GA ARPU : DTAC - GEO Channel = ("DB1R000900CG Prepaid Inflow M1 : DTAC - GEO Channel" / "DB1S000101CG Prepaid Gross Adds : DTAC - GEO Channel")
			SELECT M1_D.TM_KEY_DAY
				, REPLACE(M1_D.METRIC_CD, 'DB1R000900CG', 'DB1R001200CG') AS METRIC_CD
				, REPLACE(M1_D.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
				, CASE WHEN COALESCE(GA_D.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_D.ACTUAL_AGG_MTH / GA_D.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'DTAC' AS COMP_CD, 'A' AS VERSION
				, M1_D.AREA_CD, M1_D.AREA_NAME, M1_D.AREA_TYPE
				, M1_D.METRIC_CD||' '||M1_D.METRIC_NAME||' / '||GA_D.METRIC_CD||' '||GA_D.METRIC_NAME AS REMARK
			FROM ( -->> DB1R000900CG Prepaid Inflow M1 : DTAC - GEO Channel
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB1R000900CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1_D
			LEFT JOIN ( -->> DB1S000101CG Prepaid Gross Adds : DTAC - GEO Channel
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB1S000101CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA_D
				ON M1_D.AREA_CD = GA_D.AREA_CD
				AND M1_D.TM_KEY_DAY = GA_D.TM_KEY_DAY
				
		) PREPAID_GA_ARPU_ALL_CHNL
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
		
			-->> TRUE(Geo) : TB1R001200CG Prepaid GA ARPU : TMH - GEO Channel = ("TB1R000900CG Prepaid Inflow M1 : TMH - GEO Channel" / "TB1S000101CG Prepaid Gross Adds : TMH - GEO Channel")
			SELECT M1_T.TM_KEY_DAY
				, REPLACE(M1_T.METRIC_CD, 'TB1R000900CG', 'TB1R001200CG') AS METRIC_CD
				, REPLACE(M1_T.METRIC_NAME, 'Inflow M1', 'GA ARPU') AS METRIC_NAME
				, CASE WHEN COALESCE(GA_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M1_T.ACTUAL_AGG_MTH / GA_T.ACTUAL_AGG_MTH) END METRIC_VALUE -->> Calculation
				, 'TRUE' AS COMP_CD, 'A' AS VERSION
				, M1_T.AREA_CD, M1_T.AREA_NAME, M1_T.AREA_TYPE
				, M1_T.METRIC_CD||' '||M1_T.METRIC_NAME||' / '||GA_T.METRIC_CD||' '||GA_T.METRIC_NAME AS REMARK
			FROM ( -->> TB1R000900CG Prepaid Inflow M1 : TMH - GEO Channel
				SELECT TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB1R000900CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M1_T
			LEFT JOIN ( -->> TB1S000101CG Prepaid Gross Adds : TMH - GEO Channel
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB1S000101CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) GA_T
				ON M1_T.AREA_CD = GA_T.AREA_CD
				AND M1_T.TM_KEY_DAY = GA_T.TM_KEY_DAY
		) PREPAID_GA_ARPU_GEO_CHNL
	;

COMMIT;
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------


/* PREPAID_CVS_M2_TO_M1 */

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
	
		-->> All Channel
			-->> ALL : B1R001100CS Prepaid Conversion M2 to M1 = ("B1R001000CS Prepaid Inflow M2" / "B1R000900CS Prepaid Inflow M1")
			SELECT M2.TM_KEY_DAY
				, REPLACE(M2.METRIC_CD, 'B1R001000CS', 'B1R001100CS') AS METRIC_CD
				, REPLACE(M2.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
				, CASE WHEN COALESCE(M1.ACTUAL_AGG_MTH,0) <> 0 THEN (M2.ACTUAL_AGG_MTH / M1.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
				, 'ALL' AS COMP_CD, 'A' AS VERSION
				, M2.AREA_CD, M2.AREA_NAME, M2.AREA_TYPE
				, M2.METRIC_CD||' '||M2.METRIC_NAME||' / '||M1.METRIC_CD||' '||M1.METRIC_NAME AS REMARK
			FROM ( -->> B1R001000CS Prepaid Inflow M2
				SELECT TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
					, TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B1R001000CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M2
			LEFT JOIN ( -->> B1R000900CS Prepaid Inflow M1
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B1R000900CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= TO_CHAR(ADD_MONTHS(TO_DATE(V_SNAP_TM_KEY,'YYYYMMDD'), -1), 'YYYYMMDD') -->> Prev MTH Inflow M1 of M2
			) M1
				ON M2.AREA_CD = M1.AREA_CD
				AND M2.PREV_TM_KEY_DAY = M1.TM_KEY_DAY
				
		) PREPAID_CVS_M2_TO_M1
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
			-->> DTAC : DB1R001100CS Prepaid Conversion M2 to M1 : DTAC = ("DB1R001000CS Prepaid Inflow M2 : DTAC" / "DB1R000900CS Prepaid Inflow M1 : DTAC")
			SELECT M2_D.TM_KEY_DAY
				, REPLACE(M2_D.METRIC_CD, 'DB1R001000CS', 'DB1R001100CS') AS METRIC_CD
				, REPLACE(M2_D.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
				, CASE WHEN COALESCE(M1_D.ACTUAL_AGG_MTH,0) <> 0 THEN (M2_D.ACTUAL_AGG_MTH / M1_D.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
				, 'DTAC' AS COMP_CD, 'A' AS VERSION
				, M2_D.AREA_CD, M2_D.AREA_NAME, M2_D.AREA_TYPE
				, M2_D.METRIC_CD||' '||M2_D.METRIC_NAME||' / '||M1_D.METRIC_CD||' '||M1_D.METRIC_NAME AS REMARK
			FROM ( -->> DB1R001000CS Prepaid Inflow M2 : DTAC
				SELECT TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
					, TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB1R001000CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M2_D
			LEFT JOIN ( -->> DB1R000900CS Prepaid Inflow M1 : DTAC
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB1R000900CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= TO_CHAR(ADD_MONTHS(TO_DATE(V_SNAP_TM_KEY,'YYYYMMDD'), -1), 'YYYYMMDD') -->> Prev MTH Inflow M1 of M2
			) M1_D
				ON M2_D.AREA_CD = M1_D.AREA_CD
				AND M2_D.PREV_TM_KEY_DAY = M1_D.TM_KEY_DAY
				
		) PREPAID_CVS_M2_TO_M1
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
		
			-->> TRUE : TB1R001100CS Prepaid Conversion M2 to M1 : TMH = ("TB1R001000CS Prepaid Inflow M2 : TMH" / "TB1R000900CS Prepaid Inflow M1 : TMH")
			SELECT M2_T.TM_KEY_DAY
				, REPLACE(M2_T.METRIC_CD, 'TB1R001000CS', 'TB1R001100CS') AS METRIC_CD
				, REPLACE(M2_T.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
				, CASE WHEN COALESCE(M1_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M2_T.ACTUAL_AGG_MTH / M1_T.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
				, 'TRUE' AS COMP_CD, 'A' AS VERSION
				, M2_T.AREA_CD, M2_T.AREA_NAME, M2_T.AREA_TYPE
				, M2_T.METRIC_CD||' '||M2_T.METRIC_NAME||' / '||M1_T.METRIC_CD||' '||M1_T.METRIC_NAME AS REMARK
			FROM ( -->> TB1R001000CS Prepaid Inflow M2 : TMH
				SELECT TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
					, TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB1R001000CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M2_T
			LEFT JOIN ( -->> TB1R000900CS Prepaid Inflow M1 : TMH
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB1R000900CS'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= TO_CHAR(ADD_MONTHS(TO_DATE(V_SNAP_TM_KEY,'YYYYMMDD'), -1), 'YYYYMMDD') -->> Prev MTH Inflow M1 of M2
			) M1_T
				ON M2_T.AREA_CD = M1_T.AREA_CD
				AND M2_T.PREV_TM_KEY_DAY = M1_T.TM_KEY_DAY
		) PREPAID_CVS_M2_TO_M1_ALL_CHNL
		-----------------------------------------------------------------------------------------------------------------------
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
	
		-->> GEO Channel

			-->> ALL(Geo) : B1R001100CG Prepaid Conversion M2 to M1 - GEO Channel = ("B1R001000CG Prepaid Inflow M2 - GEO Channel" / "B1R000900CG Prepaid Inflow M1 - GEO Channel")
			SELECT M2.TM_KEY_DAY
				, REPLACE(M2.METRIC_CD, 'B1R001000CG', 'B1R001100CG') AS METRIC_CD
				, REPLACE(M2.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
				, CASE WHEN COALESCE(M1.ACTUAL_AGG_MTH,0) <> 0 THEN (M2.ACTUAL_AGG_MTH / M1.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
				, 'ALL' AS COMP_CD, 'A' AS VERSION
				, M2.AREA_CD, M2.AREA_NAME, M2.AREA_TYPE
				, M2.METRIC_CD||' '||M2.METRIC_NAME||' / '||M1.METRIC_CD||' '||M1.METRIC_NAME AS REMARK
			FROM ( -->> B1R001000CG Prepaid Inflow M2 - GEO Channel
				SELECT TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
					, TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B1R001000CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M2
			LEFT JOIN ( -->> B1R000900CG Prepaid Inflow M1 - GEO Channel
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'B1R000900CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= TO_CHAR(ADD_MONTHS(TO_DATE(V_SNAP_TM_KEY,'YYYYMMDD'), -1), 'YYYYMMDD') -->> Prev MTH Inflow M1 of M2
			) M1
				ON M2.AREA_CD = M1.AREA_CD
				AND M2.PREV_TM_KEY_DAY = M1.TM_KEY_DAY
				
		) PREPAID_CVS_M2_TO_M1
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
		
			-->> DTAC(Geo) : DB1R001100CG Prepaid Conversion M2 to M1 : DTAC - GEO Channel = ("DB1R001000CG Prepaid Inflow M2 : DTAC - GEO Channel" / "DB1R000900CG Prepaid Inflow M1 : DTAC - GEO Channel")
			SELECT M2_D.TM_KEY_DAY
				, REPLACE(M2_D.METRIC_CD, 'DB1R001000CG', 'DB1R001100CG') AS METRIC_CD
				, REPLACE(M2_D.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
				, CASE WHEN COALESCE(M1_D.ACTUAL_AGG_MTH,0) <> 0 THEN (M2_D.ACTUAL_AGG_MTH / M1_D.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
				, 'DTAC' AS COMP_CD, 'A' AS VERSION
				, M2_D.AREA_CD, M2_D.AREA_NAME, M2_D.AREA_TYPE
				, M2_D.METRIC_CD||' '||M2_D.METRIC_NAME||' / '||M1_D.METRIC_CD||' '||M1_D.METRIC_NAME AS REMARK
			FROM ( -->> DB1R001000CG Prepaid Inflow M2 : DTAC - GEO Channel
				SELECT TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
					, TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB1R001000CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M2_D
			LEFT JOIN ( -->> DB1R000900CG Prepaid Inflow M1 : DTAC - GEO Channel
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'DB1R000900CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= TO_CHAR(ADD_MONTHS(TO_DATE(V_SNAP_TM_KEY,'YYYYMMDD'), -1), 'YYYYMMDD') -->> Prev MTH Inflow M1 of M2
			) M1_D
				ON M2_D.AREA_CD = M1_D.AREA_CD
				AND M2_D.PREV_TM_KEY_DAY = M1_D.TM_KEY_DAY
				
		) PREPAID_CVS_M2_TO_M1
;
COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM (
		
			-->> TRUE(Geo) : TB1R001100CG Prepaid Conversion M2 to M1 : TMH - GEO Channel = ("TB1R001000CG Prepaid Inflow M2 : TMH - GEO Channel" / "TB1R000900CG Prepaid Inflow M1 : TMH - GEO Channel")
			SELECT M2_T.TM_KEY_DAY
				, REPLACE(M2_T.METRIC_CD, 'TB1R001000CG', 'TB1R001100CG') AS METRIC_CD
				, REPLACE(M2_T.METRIC_NAME, 'Inflow M2', 'Conversion M2 to M1') AS METRIC_NAME
				, CASE WHEN COALESCE(M1_T.ACTUAL_AGG_MTH,0) <> 0 THEN (M2_T.ACTUAL_AGG_MTH / M1_T.ACTUAL_AGG_MTH) * 100 END METRIC_VALUE -->> Calculation
				, 'TRUE' AS COMP_CD, 'A' AS VERSION
				, M2_T.AREA_CD, M2_T.AREA_NAME, M2_T.AREA_TYPE
				, M2_T.METRIC_CD||' '||M2_T.METRIC_NAME||' / '||M1_T.METRIC_CD||' '||M1_T.METRIC_NAME AS REMARK
			FROM ( -->> TB1R001000CG Prepaid Inflow M2 : TMH - GEO Channel
				SELECT TO_CHAR(ADD_MONTHS(TO_DATE(TM_KEY_MTH, 'YYYYMM'), -1), 'YYYYMM') || SUBSTR(TM_KEY_DAY,7,2) AS PREV_TM_KEY_DAY
					, TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB1R001000CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= V_SNAP_TM_KEY
			) M2_T
			LEFT JOIN ( -->> TB1R000900CG Prepaid Inflow M1 : TMH - GEO Channel
				SELECT TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_CD, ACTUAL_AGG_MTH
				FROM GEOSPCAPPO.AGG_PERF_NEWCO 
				WHERE METRIC_CD = 'TB1R000900CG'
				AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
				AND TM_KEY_DAY >= TO_CHAR(ADD_MONTHS(TO_DATE(V_SNAP_TM_KEY,'YYYYMMDD'), -1), 'YYYYMMDD') -->> Prev MTH Inflow M1 of M2
			) M1_T
				ON M2_T.AREA_CD = M1_T.AREA_CD
				AND M2_T.PREV_TM_KEY_DAY = M1_T.TM_KEY_DAY
		) PREPAID_CVS_M2_TO_M1_GEO_CHNL

	;

COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM ( -->> B0R0001001GEO Total Service Revenue Growth (YTD YoY%)
	
		SELECT TM_KEY_DAY, 'B0R0001001GEO' AS METRIC_CD, 'Total Service Revenue Growth (YTD YoY%)' AS METRIC_NAME
			, CASE WHEN COALESCE(PREV_YTD,0) <> 0 THEN (YTD - PREV_YTD) / PREV_YTD * 100 END METRIC_VALUE -->> Calculation
			, 'ALL' AS COMP_CD, 'A' AS VERSION
			, AREA_CD, AREA_NAME, AREA_TYPE
			, 'Ref : '||METRIC_CD||' '||METRIC_NAME AS REMARK
		FROM (
			SELECT TM_KEY_YR, TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME
				, ACTUAL_AGG_YR AS YTD
				, LAG(ACTUAL_AGG_YR) OVER (PARTITION BY METRIC_CD, AREA_CD, SUBSTR(TM_KEY_DAY,5,4) ORDER BY TM_KEY_YR) AS PREV_YTD
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'B0R000100GEO' --Total Revenue (Geo)
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= TO_CHAR(ADD_MONTHS(TO_DATE(V_SNAP_TM_KEY,'YYYYMMDD'),-12),'YYYYMMDD') -->> Prev YTD
		) PREP_TOTAL_REV_GROWTH
		WHERE TM_KEY_DAY >= V_SNAP_TM_KEY
		
	) TOTAL_REV_GROWTH
	;

COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM ( -->> B0R0001004 Prepaid Revenue Growth (YTD YoY%)
	
		SELECT TM_KEY_DAY, 'B0R0001004' AS METRIC_CD, 'Prepaid Revenue Growth (YTD YoY%)' AS METRIC_NAME
			, CASE WHEN COALESCE(PREV_YTD,0) <> 0 THEN (YTD - PREV_YTD) / PREV_YTD * 100 END METRIC_VALUE -->> Calculation
			, 'ALL' AS COMP_CD, 'A' AS VERSION
			, AREA_CD, AREA_NAME, AREA_TYPE
			, 'Ref : '||METRIC_CD||' '||METRIC_NAME AS REMARK
		FROM (
			SELECT TM_KEY_YR, TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME
				, ACTUAL_AGG_YR AS YTD
				, LAG(ACTUAL_AGG_YR) OVER (PARTITION BY METRIC_CD, AREA_CD, SUBSTR(TM_KEY_DAY,5,4) ORDER BY TM_KEY_YR) AS PREV_YTD
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'B1R000100' --Prepaid Revenue
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= TO_CHAR(ADD_MONTHS(TO_DATE(V_SNAP_TM_KEY,'YYYYMMDD'),-12),'YYYYMMDD') -->> Prev YTD
		) PREP_PREPAID_REV_GROWTH
		WHERE TM_KEY_DAY >= V_SNAP_TM_KEY
		
	) PREPAID_REV_GROWTH
	;

COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM ( -->> B0R0101003 Postpaid Revenue Growth B2C (YTD YoY%)
	
		SELECT TM_KEY_DAY, 'B0R0101003' AS METRIC_CD, 'Postpaid Revenue Growth B2C (YTD YoY%)' AS METRIC_NAME
			, CASE WHEN COALESCE(PREV_YTD,0) <> 0 THEN (YTD - PREV_YTD) / PREV_YTD * 100 END METRIC_VALUE -->> Calculation
			, 'ALL' AS COMP_CD, 'A' AS VERSION
			, AREA_CD, AREA_NAME, AREA_TYPE
			, 'Ref : '||METRIC_CD||' '||METRIC_NAME AS REMARK
		FROM (
			SELECT TM_KEY_YR, TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME
				, ACTUAL_AGG_YR AS YTD
				, LAG(ACTUAL_AGG_YR) OVER (PARTITION BY METRIC_CD, AREA_CD, SUBSTR(TM_KEY_DAY,5,4) ORDER BY TM_KEY_YR) AS PREV_YTD
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'B2R010100' --Postpaid Revenue B2C
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= TO_CHAR(ADD_MONTHS(TO_DATE(V_SNAP_TM_KEY,'YYYYMMDD'),-12),'YYYYMMDD') -->> Prev YTD
		) PREP_POSTPAID_REV_GROWTH_B2C
		WHERE TM_KEY_DAY >= V_SNAP_TM_KEY
		
	) POSTPAID_REV_GROWTH_B2C
	;

COMMIT;

INSERT /*+ APPEND */ INTO GEOSPCAPPO.STG_KPI_NEWCO_COMMON_KPI_ACTUAL 
	(TM_KEY_DAY, METRIC_CD, METRIC_NAME, ACTUAL, COMP_CD, VERSION, AREA_CD, AREA_DESC, AREA_TYPE, LOAD_DATE, REMARK)
	-----------------------------------------------------------------------------------------------------------------------

	SELECT /*+ parallel(4) */ TM_KEY_DAY, METRIC_CD, METRIC_NAME, METRIC_VALUE, COMP_CD, VERSION, AREA_CD, AREA_NAME, AREA_TYPE
		, CURRENT_DATE AS LOAD_DATE, REMARK
		
	FROM ( -->> B0R0001005 TOL Revenue Growth (YTD YoY%)
	
		SELECT TM_KEY_DAY, 'B0R0001005' AS METRIC_CD, 'TOL Revenue Growth (YTD YoY%)' AS METRIC_NAME
			, CASE WHEN COALESCE(PREV_YTD,0) <> 0 THEN (YTD - PREV_YTD) / PREV_YTD * 100 END METRIC_VALUE -->> Calculation
			, 'TRUE' AS COMP_CD, 'A' AS VERSION
			, AREA_CD, AREA_NAME, AREA_TYPE
			, 'Ref : '||METRIC_CD||' '||METRIC_NAME AS REMARK
		FROM (
			SELECT TM_KEY_YR, TM_KEY_MTH, TM_KEY_DAY, METRIC_CD, METRIC_NAME, AREA_TYPE, AREA_CD, AREA_NAME
				, ACTUAL_AGG_YR AS YTD
				, LAG(ACTUAL_AGG_YR) OVER (PARTITION BY METRIC_CD, AREA_CD, SUBSTR(TM_KEY_DAY,5,4) ORDER BY TM_KEY_YR) AS PREV_YTD
			FROM GEOSPCAPPO.AGG_PERF_NEWCO 
			WHERE METRIC_CD = 'TB3R000100' --TOL Revenue
			AND AREA_TYPE NOT IN ('CCAA', 'CCAATT')
			AND TM_KEY_DAY >= TO_CHAR(ADD_MONTHS(TO_DATE(V_SNAP_TM_KEY,'YYYYMMDD'),-12),'YYYYMMDD') -->> Prev YTD
		) PREP_TOL_REV_GROWTH
		WHERE TM_KEY_DAY >= V_SNAP_TM_KEY
		
	) TOL_REV_GROWTH
	;

COMMIT;
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------

END PRC_FCT_KPI_NEWCO_COMMON_KPI ;
