WITH AREA_FILTER AS (
    SELECT
        TDS_PROVINCE AS PBH,
        DISTRICT_TH AS DISTRICT,
        SUB_DISTRICT_TH AS SUB_DISTRICT,
        CCAATT AS DIM_AREA_KEY
    FROM BNIC_AII_DB.EDMAIML_CENTRAL_DATA.DIM_MOOC_AREA
    WHERE CCAATT IS NOT NULL
        AND TDS_PROVINCE ILIKE '%Area name%'
    GROUP BY ALL
),
MAIN AS (
    SELECT
        TM_KEY_DAY,
        TM_KEY_YR,
        PROPOSITION,
        SUM(ROW_YTD_SALE_IN)      AS SALE_IN,
        SUM(ROW_PREV_YTD_SALE_IN) AS PREV_SALE_IN
    FROM bnic_aii_db.insights_consumption_layer.sales_mart AS MAIN
    LEFT JOIN AREA_FILTER AS A ON A.DIM_AREA_KEY = MAIN.PARTNER_CCAATT
    WHERE TM_KEY_DAY = {YTD}
        AND (PRODUCT ILIKE '%TOL%')
        AND A.DIM_AREA_KEY IS NOT NULL
    GROUP BY TM_KEY_DAY, TM_KEY_YR, PROPOSITION
),
AGG AS (
    SELECT
        *,
        CASE WHEN PREV_TOTAL_SALE_IN <> 0 THEN
            ROUND(((TOTAL_SALE_IN / PREV_TOTAL_SALE_IN) - 1) * 100, 2) ELSE 0 END TOTAL_SALE_IN_MOM,
        CASE WHEN PREV_SALE_IN <> 0 THEN
            ROUND(((SALE_IN / PREV_SALE_IN) - 1) * 100, 2) ELSE 0 END SALE_IN_MOM
    FROM (
        SELECT
            TM_KEY_DAY,
            TM_KEY_YR,
            SUM(SALE_IN)      OVER (PARTITION BY TM_KEY_DAY, TM_KEY_YR) TOTAL_SALE_IN,
            SUM(PREV_SALE_IN) OVER (PARTITION BY TM_KEY_DAY, TM_KEY_YR) PREV_TOTAL_SALE_IN,
            PROPOSITION,
            SALE_IN,
            PREV_SALE_IN
        FROM MAIN
    )
),
RANKING AS (
    SELECT
        *,
        DENSE_RANK() OVER (PARTITION BY TM_KEY_DAY, TM_KEY_YR ORDER BY SALE_IN DESC) AS TOP_PROPOSITION_RNK,
        DENSE_RANK() OVER (PARTITION BY TM_KEY_YR ORDER BY
            CASE WHEN TOTAL_SALE_IN = 0 THEN NULL ELSE TM_KEY_DAY END DESC NULLS LAST) AS DAY_RNK
    FROM AGG
)
SELECT
    TM_KEY_DAY,
    TM_KEY_YR,
    TOTAL_SALE_IN,
    TOTAL_SALE_IN_MOM,
    PROPOSITION,
    SALE_IN,
    SALE_IN_MOM
FROM RANKING
WHERE DAY_RNK = 1
    AND TOP_PROPOSITION_RNK <= 5
ORDER BY TM_KEY_DAY, TM_KEY_YR, TOP_PROPOSITION_RNK