WITH AREA_FILTER AS (
    SELECT
        TDS_PROVINCE AS PBH,
        DISTRICT_TH AS DISTRICT,
        SUB_DISTRICT_TH AS SUB_DISTRICT,
        CCAATT AS DIM_AREA_KEY
    FROM BNIC_AII_DB.EDMAIML_CENTRAL_DATA.DIM_MOOC_AREA
    WHERE CCAATT IS NOT NULL
    AND TDS_PROVINCE ILIKE '%CHIANG MAI 2%'
    GROUP BY ALL
)

, MAIN AS (
    SELECT
        TM_KEY_DAY,
        TM_KEY_YR,
        PROPOSITION,
        SUM(ROW_YTD_GA)      AS GA,
        SUM(ROW_PREV_YTD_GA) AS PREV_GA,
        SUM(ROW_DAILY_GA)    AS DAILY_GA
    FROM bnic_aii_db.insights_consumption_layer.sales_mart AS MAIN
    INNER JOIN AREA_FILTER AS A 
        ON A.DIM_AREA_KEY = MAIN.PARTNER_CCAATT
    WHERE TM_KEY_DAY <= 20260310 AND TM_KEY_YR = 2026
    AND (PRODUCT ILIKE '%PREPAID%')
    GROUP BY TM_KEY_DAY, TM_KEY_YR, PROPOSITION
)

, AGG AS (
    SELECT 
        *
        , CASE WHEN PREV_TOTAL_GA <> 0 THEN ROUND(((TOTAL_GA / PREV_TOTAL_GA) - 1) * 100, 2) ELSE 0 END TOTAL_GA_MOM
        , CASE WHEN PREV_GA <> 0 THEN ROUND(((GA / PREV_GA) - 1) * 100, 2) ELSE 0 END GA_MOM
    FROM (
        SELECT
        TM_KEY_DAY,
        TM_KEY_YR,
        SUM(GA)      OVER (PARTITION BY TM_KEY_DAY, TM_KEY_YR) TOTAL_GA,
        SUM(DAILY_GA) OVER (PARTITION BY TM_KEY_DAY, TM_KEY_YR) TOTAL_DAILY_GA,
        SUM(PREV_GA) OVER (PARTITION BY TM_KEY_DAY, TM_KEY_YR) PREV_TOTAL_GA,
        PROPOSITION,
        GA,
        PREV_GA
    FROM MAIN
    )
)

, RANKING AS (
    SELECT
        *,
        DENSE_RANK() OVER (PARTITION BY TM_KEY_DAY, TM_KEY_YR ORDER BY GA DESC) AS TOP_PROPOSITION_RNK,
        DENSE_RANK() OVER (PARTITION BY TM_KEY_YR ORDER BY
        CASE WHEN TOTAL_DAILY_GA = 0 THEN NULL ELSE TM_KEY_DAY END DESC NULLS LAST) AS DAY_RNK
    FROM AGG
)

SELECT
    TM_KEY_DAY,
    TM_KEY_YR,
    TOTAL_GA,
    TOTAL_GA_MOM,
    PROPOSITION,
    GA,
    GA_MOM
FROM RANKING
WHERE DAY_RNK = 1
AND TOP_PROPOSITION_RNK <= 5
ORDER BY TM_KEY_DAY, TM_KEY_YR, TOP_PROPOSITION_RNK LIMIT 100;