WITH AREA_FILTER AS (
SELECT
TDS_PROVINCE AS PBH,
CCAATT AS DIM_AREA_KEY
FROM BNIC_AII_DB.EDMAIML_CENTRAL_DATA.DIM_MOOC_AREA
WHERE CCAATT IS NOT NULL
AND TDS_PROVINCE ILIKE '%CHIANG MAI 1%'
GROUP BY ALL
)
, MAIN AS (
SELECT
TM_KEY_DAY,
PARTNER_CODE,
PARTNER_NAME,
GP_SKU,
SUM(ROW_MTD_GA) AS GA,
SUM(ROW_PREV_MTD_GA) AS PREV_GA
FROM BNIC_AII_DB.INSIGHTS_CONSUMPTION_LAYER.SALES_MART AS MAIN
INNER JOIN AREA_FILTER AS A
ON A.DIM_AREA_KEY = MAIN.PARTNER_CCAATT
WHERE
TM_KEY_DAY = 20250615
AND (PRODUCT ILIKE '%PREPAID%')
AND TDS_SPECIAL_CHANNEL ILIKE '%COM7%'
GROUP BY TM_KEY_DAY, PARTNER_CODE, PARTNER_NAME, GP_SKU
)
, AGG AS (
SELECT
*,
CASE WHEN PREV_PARTNER_GA <> 0 THEN
ROUND(((PARTNER_GA/PREV_PARTNER_GA)-1)*100,2) ELSE 0 END AS PARTNER_GA_MOM,
CASE WHEN PREV_GA <> 0 THEN
ROUND(((GA/PREV_GA)-1)*100,2) ELSE 0 END AS GA_MOM
FROM
(SELECT
TM_KEY_DAY,
PARTNER_CODE,
PARTNER_NAME,
SUM(GA) OVER (PARTITION BY TM_KEY_DAY, PARTNER_CODE, PARTNER_NAME) AS PARTNER_GA,
SUM(PREV_GA) OVER (PARTITION BY TM_KEY_DAY, PARTNER_CODE, PARTNER_NAME) AS PREV_PARTNER_GA,
GP_SKU,
GA,
PREV_GA
FROM MAIN)
)
, RANKING AS (
SELECT
*,
DENSE_RANK() OVER (PARTITION BY TM_KEY_DAY ORDER BY PARTNER_GA DESC) AS TOP_PARTNER_RNK,
ROW_NUMBER() OVER (PARTITION BY TM_KEY_DAY ORDER BY
CASE WHEN PARTNER_GA = 0 THEN NULL ELSE PARTNER_GA END ASC NULLS LAST
) AS BOT_PARTNER_RNK,
DENSE_RANK() OVER (PARTITION BY TM_KEY_DAY, PARTNER_CODE, PARTNER_NAME ORDER BY GA DESC) AS TOP_GP_SKU_RNK,
ROW_NUMBER() OVER (PARTITION BY TM_KEY_DAY, PARTNER_CODE, PARTNER_NAME ORDER BY
CASE WHEN GA = 0 THEN NULL ELSE GA END ASC NULLS LAST
) AS BOT_GP_SKU_RNK
FROM AGG
)
, FILTER AS (
SELECT TM_KEY_DAY, PARTNER_CODE, PARTNER_NAME
FROM RANKING
WHERE
TOP_PARTNER_RNK <= 3
OR (BOT_PARTNER_RNK <= 3 AND PARTNER_GA <> 0)

GROUP BY TM_KEY_DAY, PARTNER_CODE, PARTNER_NAME
)
SELECT
R.TM_KEY_DAY,
R.PARTNER_CODE,
R.PARTNER_NAME,
R.PARTNER_GA,
R.PARTNER_GA_MOM,
R.GP_SKU,
R.GA,
R.GA_MOM
FROM RANKING R
INNER JOIN FILTER F
ON R.TM_KEY_DAY = F.TM_KEY_DAY
AND R.PARTNER_CODE = F.PARTNER_CODE
AND R.PARTNER_NAME = F.PARTNER_NAME
WHERE TOP_GP_SKU_RNK <= 3 OR (BOT_GP_SKU_RNK <= 3 AND GA <> 0)
ORDER BY R.TM_KEY_DAY DESC, R.TOP_PARTNER_RNK LIMIT 100;